Repository short-d/short, pull requests merged in 2019-12, with the labels that each got.

#404 Enable coverage report for master branch
  .drone.yml
Labels: enhancement

#405 Remove unused Dockerfile
  Dockerfile-build
Labels: Maintainability

#408 Rewrite testing section in README
  README.md
  doc/testing/component-test-in-process.png
  doc/testing/component-test-out-of-process.png
  doc/testing/integration-test.png
  doc/testing/test-pyramid.png
  doc/testing/test-strategy.png
  doc/testing/unit-test-two-types.png
  doc/testing/unit-test.png
Labels: documentation

#409 Add IsUserIDExist to UserFake and fix UpdateUserID bug
  backend/app/usecase/repository/user_fake.go
Labels: enhancement

#410 Add account mapping repository
  backend/app/usecase/repository/accountmapping.go
  backend/app/usecase/repository/accountmapping_fake.go
Labels: enhancement

#411 Add account linker
  backend/app/usecase/account/linker.go
  backend/app/usecase/account/linker_test.go
Labels: enhancement

#412 Add leader vs manager diagram to README
  README.md
  doc/leader-vs-manager.jpg
Labels: documentation

#413 Fix wording in README
  README.md
Labels: documentation

#414 Add downwards migration SQLs
  backend/app/adapter/migration/1_create_url_table.sql
  backend/app/adapter/migration/2_create_user_table.sql
  backend/app/adapter/migration/3_rename_url_table_and_columns.sql
  backend/app/adapter/migration/4_rename_user_table_and_columns.sql
  backend/app/adapter/migration/5_create_user_url_relation_table.sql
  backend/app/adapter/migration/6_add_user_id_column.sql
  backend/app/adapter/migration/7_create_github_oauth_user_relation_table.sql
  backend/app/adapter/migration/8_create_public_url_table.sql
  backend/app/adapter/migration/9_change_url_alias_type.sql
Labels: enhancement

#415 Remove unused code
  backend/cmd/start.go
Labels: Maintainability

#416 Upgrade to use environment variable loader provided by app
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/main.go
Labels: Maintainability

#417 Update dependencies
  backend/app/app.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
Labels: dependencies

#419 fix(error): return error instead of nil
  backend/app/adapter/db/url.go
Labels: bug

#418 Add Google OAuth IdentityProvider
  backend/app/adapter/google/identityprovider.go
Labels: enhancement

#425 Format frontend
  frontend/src/service/Error.service.ts
  frontend/src/service/Url.service.ts
Labels: Maintainability, size/XS

#424 Update frontend dependencies
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#426 Move MustParseSQLTime to sqltest package
  backend/app/adapter/db/sqltest/time.go
  backend/app/adapter/db/url_test.go
  backend/app/adapter/db/userurl_test.go
Labels: Maintainability

#427 Separate unit tests from integration tests
  backend/app/adapter/db/url_test.go
  backend/app/adapter/db/user_test.go
  backend/app/adapter/db/userurl_test.go
  backend/app/adapter/graphql/graphql_test.go
  backend/app/adapter/graphql/resolver/authmutation_test.go
  backend/app/adapter/graphql/resolver/authquery_test.go
  backend/app/adapter/graphql/resolver/query_test.go
  backend/app/adapter/graphql/resolver/url_test.go
  backend/app/adapter/recaptcha/recaptcha_test.go
  backend/app/usecase/account/linker_test.go
  backend/app/usecase/account/provider_test.go
  backend/app/usecase/auth/authenticator_test.go
  backend/app/usecase/keygen/reomote_test.go
  backend/app/usecase/sso/sso_test.go
  backend/app/usecase/url/urlcreator_test.go
  backend/app/usecase/url/urlretriever_test.go
  backend/app/usecase/validator/alias_test.go
  backend/app/usecase/validator/longlink_test.go
  backend/scripts/integration-test
  backend/scripts/test
Labels: maintainability, size/M

#428 Rename db tests to integration tests
  backend/app/adapter/db/url_integration_test.go
  backend/app/adapter/db/user_integration_test.go
  backend/app/adapter/db/userurl_integration_test.go
Labels: maintainability

#429 Convert URL repository tests to integration test against real DB
  .gitignore
  backend/app/adapter/db/.env
  backend/app/adapter/db/url_integration_test.go
Labels: maintainability, size/L

#430 Add instructions to run unit tests and integration tests
  README.md
Labels: documentation, size/S

#431 Remove redundant parser package
  backend/app/adapter/graphql/parser/time.go
  backend/app/adapter/graphql/scalar/time.go
Labels: maintainability, size/M

#421 Add Account for Google OAuth
  backend/app/adapter/google/account.go
Labels: enhancement

#432 Add related projects section to README
  README.md
Labels: documentation, size/XS

#433 Add Google OAuth API
  backend/app/adapter/google/api.go
Labels: size/S

#434 Add comments to GraphQL resolver package.
  backend/app/adapter/graphql/resolver/error.go
  backend/app/adapter/graphql/resolver/resolver.go
  backend/app/adapter/graphql/resolver/url.go
Labels: maintainability, size/M

#435 Add comments
  backend/app/adapter/graphql/resolver/error.go
  backend/app/adapter/recaptcha/recaptcha.go
  backend/app/entity/url.go
  backend/app/entity/user.go
  backend/app/usecase/auth/authenticator.go
  backend/app/usecase/auth/authenticator_fake.go
  backend/app/usecase/auth/payload.go
  backend/app/usecase/keygen/keygen.go
  backend/app/usecase/requester/verifier.go
  backend/app/usecase/service/oauth.go
  backend/app/usecase/service/oauth_fake.go
  backend/app/usecase/service/recaptcha.go
  backend/cmd/cmd.go
Labels: maintainability, size/S

#436 Remove unused JSONTime
  backend/app/usecase/service/recaptcha.go
Labels: maintainability, size/S

#437 Fix ineffectual assignment warning
  backend/app/usecase/url/urlcreator_test.go
Labels: maintainability, size/XS

#438 Refactor fake reCaptcha service
  backend/app/adapter/graphql/graphql_test.go
  backend/app/adapter/recaptcha/recaptcha_fake.go
  backend/app/usecase/service/recaptcha_fake.go
Labels: maintainability, size/M

#439 Add comment to error code enums
  backend/app/adapter/graphql/resolver/error.go
Labels: maintainability, size/XS

#440 Convert all repository tests to DB integration tests
  backend/app/adapter/db/main_test.go
  backend/app/adapter/db/sqltest/time.go
  backend/app/adapter/db/url_integration_test.go
  backend/app/adapter/db/user_integration_test.go
  backend/app/adapter/db/userurl_integration_test.go
Labels: maintainability, size/XL

#441 Fix DB bugs and integration tests
  backend/app/adapter/db/main_test.go
  backend/app/adapter/db/url.go
  backend/app/adapter/db/url_integration_test.go
  backend/app/adapter/db/user.go
  backend/app/adapter/db/user_integration_test.go
  backend/app/adapter/db/userurl_integration_test.go
  backend/scripts/integration-test
  backend/scripts/test
Labels: size/L

#444 Add remaining dependencies for Google OAuth API
  backend/app/adapter/routing/route.go
  backend/app/app.go
  backend/cmd/cmd.go
  backend/dep/provider/google.go
  backend/dep/provider/routes.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: size/L

#445 Fix app link in README
  README.md
Labels: documentation, size/XS

#446 Turn on Google sign in button
  frontend/src/service/StaticConfigDecision.service.ts
Labels: size/XS

#447 Update dependencies
  backend/go.mod
  backend/go.sum
Labels: dependencies, size/XS

#448 Enable parallel execution of unit tests
  backend/app/usecase/account/linker_test.go
  backend/app/usecase/account/provider_test.go
  backend/app/usecase/keygen/reomote_test.go
  backend/app/usecase/sso/sso_test.go
  backend/app/usecase/url/urlcreator_test.go
  backend/app/usecase/url/urlretriever_test.go
  backend/app/usecase/validator/alias_test.go
  backend/app/usecase/validator/longlink_test.go
Labels: testing

#449 Read Google sign in configurations from environment variables
  backend/main.go
Labels: size/XS

#450 Fix google sign in
  backend/app/adapter/google/account.go
  backend/app/adapter/google/identityprovider.go
Labels: bug, size/S

#451 Fix nil dereference crashing
  backend/app/adapter/db/time.go
  backend/app/adapter/db/url.go
  backend/app/adapter/db/url_integration_test.go
  backend/app/adapter/db/user.go
  backend/app/adapter/db/user_integration_test.go
Labels: bug

#452 Improve wording of "aliasNotAvailable" error message
  frontend/src/service/Error.service.ts
Labels: enhancement, size/XS

#458 Support running integration test on CI
  .drone.yml
  backend/Dockerfile-integration-test
Labels: enhancement, size/M

#456 Migrate to OpenID API for Google sign in
  backend/app/adapter/google/account.go
Labels: size/XS

#459 Rename CI jobs to maintain consistency
  .drone.yml
  README.md
  backend/Dockerfile-unit-test
  backend/scripts/unit-test
Labels: documentation, maintainability

#460 Fix broken unit-test-diagram
  doc/testing/unit-test.png
Labels: documentation

#461 Include integration tests in code coverage
  .drone.yml
  Dockerfile-coverage
  backend/app/adapter/db/main_test.go
  backend/app/adapter/db/url_integration_test.go
  backend/app/adapter/db/user_integration_test.go
  backend/app/adapter/db/userurl_integration_test.go
  backend/app/adapter/graphql/graphql_test.go
  backend/app/adapter/graphql/resolver/authmutation_test.go
  backend/app/adapter/graphql/resolver/authquery_test.go
  backend/app/adapter/graphql/resolver/query_test.go
  backend/app/adapter/graphql/resolver/url_test.go
  backend/app/adapter/recaptcha/recaptcha_test.go
  backend/app/usecase/account/linker_test.go
  backend/app/usecase/account/provider_test.go
  backend/app/usecase/auth/authenticator_test.go
  backend/app/usecase/keygen/reomote_test.go
  backend/app/usecase/sso/sso_test.go
  backend/app/usecase/url/urlcreator_test.go
  backend/app/usecase/url/urlretriever_test.go
  backend/app/usecase/validator/alias_test.go
  backend/app/usecase/validator/longlink_test.go
  backend/scripts/code-coverage
Labels: maintainability, size/M

#462 Move code review section to CONTRIBUTING.md
  CONTRIBUTING.md
  README.md
Labels: documentation, size/L

#463 Update wording of CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, size/XS
