Repository short-d/short, pull requests merged in 2019-10, with the labels that each got.

#207 Add comments in exported variables and func in dep package
  dep/provider/authenticator.go
  dep/provider/graphql.go
  dep/provider/jwt.go
  dep/provider/oauth.go
  dep/provider/recaptcha.go
  dep/provider/routes.go
Labels: Hacktoberfest, LGTM, documentation

#217 Add tools section to README
  README.md
Labels: Hacktoberfest, documentation

#213 Add Github OAuth samples configuration in README.md
  README.md
Labels: Hacktoberfest, LGTM, documentation, good first issue

#206 Add tests for fake URL creator and retriever
  app/usecase/url/urlcreator_fake_test.go
  app/usecase/url/urlretriever_fake_test.go
Labels: Hacktoberfest, good first issue, in review

#219 Add instruction to set DOCKER_USERNAME variable in README
  README.md
Labels: Hacktoberfest, documentation, good first issue, ready for review

#223 Enable code coverage for pull request
  .drone.yml
Labels: Hacktoberfest

#224 Add Slack channel to README
  README.md
Labels: Hacktoberfest, documentation, good first issue

#232 Add instructions to configure dev environment
  README.md
  backend/go.mod
  backend/go.sum
  backend/scripts/dev
Labels: documentation

#244 Add ElephantSQL as an alternative to local PostgreSQL server
  README.md
Labels: documentation

#249 Update ER diagram
  README.md
  doc/eng/db/er-v1.png
  doc/eng/db/er-v1.txt
  doc/eng/db/er-v2.png
  doc/eng/db/er-v2.txt
Labels: documentation

#250 Swap domain name to short-d.com
  README.md
  frontend/.env.production
Labels: Hacktoberfest, enhancement

#231 add tests for two files in app/adapter/graphql/resolver directory
  backend/app/adapter/graphql/resolver/url_test.go
Labels: Hacktoberfest, testing

#258 Fix footer style error
  frontend/src/component/pages/shared/Footer.scss
  frontend/src/component/pages/shared/sign-in/GithubSignInButton.tsx
  frontend/src/component/pages/shared/sign-in/SignInButton.scss
  frontend/src/component/pages/shared/sign-in/SignInButton.tsx
  frontend/src/component/pages/shared/sign-in/SignInModel.tsx
  frontend/src/component/styles/color.scss
  frontend/src/component/styles/shadow.scss
  frontend/src/component/ui/Modal.scss
Labels: bug

#259 Add Google single sign on button
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/Home.tsx
  frontend/src/component/pages/shared/sign-in/GithubSignInButton.tsx
  frontend/src/component/pages/shared/sign-in/GoogleSignInButton.tsx
  frontend/src/component/pages/shared/sign-in/SignInButton.tsx
  frontend/src/component/pages/shared/sign-in/SignInModal.scss
  frontend/src/component/pages/shared/sign-in/SignInModal.tsx
  frontend/src/component/pages/shared/sign-in/github.svg
  frontend/src/component/pages/shared/sign-in/google.svg
  frontend/src/dep.ts
  frontend/src/service/Auth.service.ts
  frontend/src/service/FeatureDecision.service.ts
  frontend/src/service/StaticConfigDecision.service.ts
Labels: Hacktoberfest, enhancement

#266 Add user id db column and github_oauth_user_relation table
  backend/app/adapter/migration/6_add_user_id_column.sql
  backend/app/adapter/migration/7_create_github_oauth_user_relation_table.sql
Labels: bug

#268 Refactor frontend
  frontend/package.json
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/Home.tsx
  frontend/src/dep.ts
  frontend/src/entity/Err.ts
  frontend/src/index.tsx
  frontend/src/service/Auth.service.ts
  frontend/src/service/Captcha.service.ts
  frontend/src/service/Error.service.ts
  frontend/src/service/Routing.service.ts
  frontend/src/service/Url.service.ts
  frontend/src/state/actions.ts
  frontend/src/state/reducers.test.ts
  frontend/src/state/reducers.ts
  frontend/yarn.lock
Labels: Maintainability

#270 Fix UI no response bug
  frontend/src/service/Url.service.ts
Labels: bug

#272 Clarify contributing guidelines
  README.md
Labels: documentation

#275 Fix error message
  frontend/src/service/Error.service.ts
Labels: bug

#288 FB login
  .drone.yml
  README.md
  backend/app/adapter/facebook/api.go
  backend/app/adapter/oauth/facebook.go
  backend/app/adapter/oauth/facebook_test.go
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
  backend/app/app.go
  backend/cmd/cmd.go
  backend/cmd/start.go
  backend/dep/provider/oauth.go
  backend/dep/provider/routes.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
  backend/main.go
  docker-compose.yml
Labels: enhancement
