Repository short-d/short, pull requests merged in 2019-11, with the labels that each got.

#310 Replace external kgs hostname with cluster hostname
  k8s/backend-deployment.staging.yaml
Labels: enhancement

#307 Add public_url table
  backend/app/adapter/migration/8_create_public_url_table.sql
Labels: enhancement

#319 Disable Github sign in
  frontend/src/component/UIFactory.tsx
  frontend/src/service/FeatureDecision.service.ts
  frontend/src/service/StaticConfigDecision.service.ts
Labels: bug

#323 Update URL creator to accept user instead of email
  backend/app/adapter/db/userurl.go
  backend/app/adapter/db/userurl_test.go
  backend/app/adapter/graphql/resolver/mutation.go
  backend/app/usecase/repo/userurl.go
  backend/app/usecase/repo/userurl_fake.go
  backend/app/usecase/url/urlcreator.go
  backend/app/usecase/url/urlcreator_fake.go
  backend/app/usecase/url/urlcreator_fake_test.go
  backend/app/usecase/url/urlcreator_test.go
Labels: Maintainability

#325 Rename CreateUrl to CreateURL
  backend/app/usecase/url/urlcreator_test.go
Labels: Maintainability

#327 Move input verification logic into use case
  backend/app/adapter/graphql/graphql_test.go
  backend/app/adapter/graphql/resolver/mutation.go
  backend/app/usecase/url/urlcreator.go
  backend/app/usecase/url/urlcreator_fake.go
  backend/app/usecase/url/urlcreator_test.go
Labels: Maintainability

#329 Move getURL logic into use case
  backend/app/adapter/graphql/graphql_test.go
  backend/app/adapter/graphql/resolver/query.go
  backend/app/adapter/graphql/resolver/query_test.go
  backend/app/adapter/oauth/github_test.go
  backend/app/adapter/routing/handle.go
  backend/app/usecase/repo/url_fake.go
  backend/app/usecase/url/urlretriever.go
  backend/app/usecase/url/urlretriever_fake.go
  backend/app/usecase/url/urlretriever_fake_test.go
  backend/app/usecase/url/urlretriever_test.go
Labels: Maintainability

#332 Format SQL
  backend/app/adapter/migration/8_create_public_url_table.sql
Labels: Maintainability

#336 Update promotion images
  frontend/public/promo/large-tile.png
  frontend/public/promo/marquee.png
  frontend/public/promo/small-tile.png
  promo/design.sketch
  promo/large-tile.png
  promo/marquee.png
  promo/small-tile.png
Labels: enhancement

#337 Introduce builder pattern for backend and frontend containers
  .env.dist
  README.md
  backend/Dockerfile
  frontend/Dockerfile
  frontend/package.json
Labels: enhancement

#338 Fix frontend Dockerfile
  frontend/Dockerfile
  frontend/package.json
Labels: bug

#339 Fix frontend Dockerfile
  frontend/Dockerfile
Labels: bug

#343 Replace url alias with URL
  backend/app/adapter/db/userurl.go
  backend/app/adapter/db/userurl_test.go
  backend/app/usecase/repo/userurl.go
  backend/app/usecase/repo/userurl_fake.go
  backend/app/usecase/url/urlcreator.go
Labels: Maintainability

#314 Add IsPublic parameter to GraphQL API
  backend/app/adapter/graphql/resolver/mutation.go
  backend/app/usecase/url/urlcreator.go
  backend/app/usecase/url/urlcreator_test.go
Labels: enhancement

#345 Decouple queries & mutations from authentication
  backend/app/adapter/db/userurl_test.go
  backend/app/adapter/graphql/resolver/User.go
  backend/app/adapter/graphql/resolver/authmutation.go
  backend/app/adapter/graphql/resolver/authmutation_test.go
  backend/app/adapter/graphql/resolver/authquery.go
  backend/app/adapter/graphql/resolver/authquery_test.go
  backend/app/adapter/graphql/resolver/mutation.go
  backend/app/adapter/graphql/resolver/query.go
  backend/app/adapter/graphql/resolver/query_test.go
  backend/app/adapter/graphql/resolver/resolver.go
  backend/app/adapter/graphql/resolver/url.go
  backend/app/adapter/graphql/resolver/viewer.go
  backend/app/adapter/graphql/schema.go
  backend/app/usecase/url/urlcreator.go
  frontend/src/service/Url.service.ts
Labels: Maintainability

#350 Configure tslint
  .drone.yml
  frontend/.prettierrc.json
  frontend/Dockerfile-lint
  frontend/package.json
  frontend/scripts/lint
  frontend/src/component/App.tsx
  frontend/src/component/UIFactory.tsx
  frontend/src/component/form/TextField.tsx
  frontend/src/component/pages/Home.tsx
  frontend/src/component/pages/NotFoundPage.tsx
  frontend/src/component/pages/shared/Footer.tsx
  frontend/src/component/pages/shared/Header.tsx
  frontend/src/component/pages/shared/ShortLinkUsage.tsx
  frontend/src/component/pages/shared/promos/ExtPromo.tsx
  frontend/src/component/pages/shared/sign-in/FacebookSignInButton.tsx
  frontend/src/component/pages/shared/sign-in/GithubSignInButton.tsx
  frontend/src/component/pages/shared/sign-in/SignInButton.tsx
  frontend/src/component/pages/shared/sign-in/SignInModal.tsx
  frontend/src/dep.ts
  frontend/src/index.tsx
  frontend/src/service/Auth.service.ts
  frontend/src/service/Captcha.service.ts
  frontend/src/service/Error.service.ts
  frontend/src/service/Url.service.ts
  frontend/src/service/Version.service.ts
  frontend/src/state/actions.ts
  frontend/src/state/reducers.test.ts
  frontend/src/state/reducers.ts
  frontend/tslint.json
  frontend/yarn.lock
Labels: Maintainability

#351 Integrate Stylelint with Prettierr
  frontend/.stylelintrc
  frontend/package.json
  frontend/scripts/lint
  frontend/src/component/form/TextField.scss
  frontend/src/component/pages/Home.scss
  frontend/src/component/pages/NotFoundPage.scss
  frontend/src/component/pages/shared/Footer.scss
  frontend/src/component/pages/shared/Header.scss
  frontend/src/component/pages/shared/promos/ExtPromo.scss
  frontend/src/component/pages/shared/sign-in/SignInButton.scss
  frontend/src/component/styles/dimension.scss
  frontend/src/component/styles/font.scss
  frontend/src/component/styles/shadow.scss
  frontend/src/component/ui/Button.scss
  frontend/src/component/ui/Notice.scss
  frontend/src/component/ui/Section.scss
  frontend/src/component/ui/Spinner.scss
  frontend/yarn.lock
Labels: Maintainability

#359 Update dependencies
  backend/go.mod
  backend/go.sum
Labels: dependencies

#360 Add SingleSignOn use case
  backend/app/entity/ssouser.go
  backend/app/usecase/service/identityprovider.go
  backend/app/usecase/service/identityprovider_fake.go
  backend/app/usecase/service/ssoaccount.go
  backend/app/usecase/service/ssoaccount_fake.go
  backend/app/usecase/sso/sso.go
  backend/app/usecase/sso/sso_test.go
Labels: enhancement

#363 Fix error collecting err codes
  frontend/src/service/Error.service.ts
  frontend/src/service/Url.service.ts
Labels: bug

#362 Replace oauth with Single Sign On
  backend/app/adapter/facebook/account.go
  backend/app/adapter/facebook/api.go
  backend/app/adapter/facebook/identityprovider.go
  backend/app/adapter/github/account.go
  backend/app/adapter/github/api.go
  backend/app/adapter/github/identityprovider.go
  backend/app/adapter/oauth/facebook_test.go
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
  backend/app/entity/profile.go
  backend/app/usecase/service/profile.go
  backend/app/usecase/service/profile_fake.go
  backend/app/usecase/signin/oauth.go
  backend/app/usecase/signin/oauth_test.go
  backend/dep/provider/facebook.go
  backend/dep/provider/github.go
  backend/dep/provider/oauth.go
  backend/dep/provider/routes.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: Maintainability

#365 Rename methods of User repository
  backend/app/adapter/db/user.go
  backend/app/adapter/db/user_test.go
  backend/app/usecase/account/repo.go
  backend/app/usecase/repo/user.go
Labels: Maintainability

#366 Add fake user repository
  backend/app/usecase/repo/user_fake.go
Labels: Maintainability

#368 Add UpdateUserID to user repository
  backend/app/adapter/db/table/user.go
  backend/app/adapter/db/user.go
  backend/app/adapter/db/user_test.go
  backend/app/usecase/repo/user.go
  backend/app/usecase/repo/user_fake.go
Labels: Maintainability

#371 Replace account interface with account provider
  backend/app/adapter/routing/route.go
  backend/app/usecase/account/provider.go
  backend/app/usecase/account/provider_test.go
  backend/app/usecase/account/repo.go
  backend/app/usecase/service/account.go
  backend/app/usecase/service/account_fake.go
  backend/app/usecase/sso/sso.go
  backend/app/usecase/sso/sso_test.go
  backend/dep/provider/routes.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: Maintainability

#373 Add extra diagram for clean architecture
  README.md
  doc/eng/clean-architecture/boundary.jpg
  doc/eng/clean-architecture/clean-architecture.jpg
  doc/eng/clean-architecture/example.png
  doc/eng/microservices.jpg
Labels: documentation

#374 Rename repo to repository
  backend/app/adapter/db/url.go
  backend/app/adapter/db/user.go
  backend/app/adapter/db/userurl.go
  backend/app/adapter/graphql/resolver/authquery_test.go
  backend/app/adapter/graphql/resolver/query_test.go
  backend/app/usecase/account/provider.go
  backend/app/usecase/account/provider_test.go
  backend/app/usecase/repository/url.go
  backend/app/usecase/repository/url_fake.go
  backend/app/usecase/repository/user.go
  backend/app/usecase/repository/user_fake.go
  backend/app/usecase/repository/userurl.go
  backend/app/usecase/repository/userurl_fake.go
  backend/app/usecase/sso/sso_test.go
  backend/app/usecase/url/urlcreator.go
  backend/app/usecase/url/urlcreator_test.go
  backend/app/usecase/url/urlretriever.go
  backend/app/usecase/url/urlretriever_test.go
  backend/dep/wire.go
Labels: Maintainability

#375 Floobits
  .floo
  .flooignore
  README.md
Labels: enhancement

#378 Add screenshots for facebook app config
  README.md
  doc/facebook/credentials.png
  doc/facebook/login.png
Labels: documentation

#379 Add screenshots for configuring Recaptcha
  README.md
  doc/recaptcha/credentials.png
  doc/recaptcha/register-site.png
  doc/recaptcha/settings.png
Labels: documentation

#380 Add screenshots for Github OAuth config
  README.md
  doc/github/credentials.png
  doc/github/new-oauth-app.png
  doc/github/oauth-apps.png
Labels: documentation

#381 Compress images referenced in the README
  README.md
  doc/eng/clean-architecture/example.jpg
  doc/eng/clean-architecture/example.png
  doc/eng/db/er-v1.jpg
  doc/eng/db/er-v1.png
  doc/eng/microservices.jpg
  doc/facebook/credentials.jpg
  doc/facebook/credentials.png
  doc/facebook/login.jpg
  doc/facebook/login.png
  doc/github/credentials.jpg
  doc/github/credentials.png
  doc/github/new-oauth-app.jpg
  doc/github/new-oauth-app.png
  doc/github/oauth-apps.jpg
  doc/github/oauth-apps.png
  doc/recaptcha/credentials.jpg
  doc/recaptcha/credentials.png
  doc/recaptcha/register-site.jpg
  doc/recaptcha/register-site.png
  doc/recaptcha/settings.jpg
  doc/recaptcha/settings.png
Labels: documentation

#382 Fix twitter card meta tags
  frontend/public/index.html
Labels: bug

#383 Switch Twitter card preview to large image
  frontend/public/index.html
Labels: enhancement

#384 Add Twitter card image
  frontend/public/index.html
  frontend/public/promo/twitter-card.png
  promo/twitter-card.png
Labels: enhancement

#386 Fix preview message
  frontend/public/index.html
Labels: bug

#388 Update Google search title
  frontend/public/index.html
Labels: bug

#390 Add SEO section in README
  README.md
  doc/seo/google.jpg
Labels: documentation

#392 Add code review guideline to README
  README.md
Labels: documentation

#393 Format README
  README.md
Labels: documentation

#282 Add FindAliasesByUser to UserURLRelation repository
  .gitignore
  backend/app/adapter/db/user_test.go
  backend/app/adapter/db/userurl.go
  backend/app/adapter/db/userurl_test.go
  backend/app/usecase/repository/userurl.go
  backend/app/usecase/repository/userurl_fake.go
  backend/app/usecase/url/urlcreator_test.go
Labels: enhancement

#394 Clean up the comments
  backend/app/adapter/db/userurl.go
  backend/app/usecase/repository/userurl_fake.go
Labels: Maintainability

#395 Refactor and clean up unit test
  backend/app/usecase/repository/url_fake.go
  backend/app/usecase/repository/userurl_fake.go
  backend/app/usecase/url/urlcreator_test.go
Labels: Maintainability

#349 Add sign out button on the header
  frontend/src/component/pages/Home.tsx
  frontend/src/component/pages/shared/Header.scss
  frontend/src/component/pages/shared/Header.tsx
Labels: enhancement

#398 Add missing example picture
  README.md
  doc/eng/clean-architecture/finance-app.jpg
Labels: documentation

#399 Cut finance app image
  doc/eng/clean-architecture/finance-app.jpg
Labels: documentation

#400 Rename dependency management to OOD
  README.md
Labels: documentation

#401 Add testing section to README
  README.md
Labels: documentation

#402 Add feature toggle section to README
  README.md
Labels: documentation

#403 Fix grammar & wording
  README.md
Labels: documentation
