Repository short-d/short, pull requests merged in 2020-04, with the labels that each got.

#610 Add resolvers for ChangeLog
  backend/app/adapter/db/changelog.go
  backend/app/adapter/graphql/graphql.go
  backend/app/adapter/graphql/graphql_test.go
  backend/app/adapter/graphql/resolver/authmutation.go
  backend/app/adapter/graphql/resolver/authquery.go
  backend/app/adapter/graphql/resolver/authquery_test.go
  backend/app/adapter/graphql/resolver/change.go
  backend/app/adapter/graphql/resolver/changelog.go
  backend/app/adapter/graphql/resolver/mutation.go
  backend/app/adapter/graphql/resolver/query.go
  backend/app/adapter/graphql/resolver/query_test.go
  backend/app/adapter/graphql/resolver/resolver.go
  backend/app/adapter/graphql/schema.go
  backend/app/entity/change.go
  backend/app/usecase/changelog/changelog.go
  backend/app/usecase/changelog/changelog_test.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: Go, enhancement, size/L

#617 Add Email payload
  backend/app/adapter/graphql/resolver/authquery_test.go
  backend/app/adapter/graphql/resolver/query_test.go
  backend/app/usecase/auth/payload/email.go
  backend/app/usecase/auth/payload/email_test.go
  backend/app/usecase/auth/payload/factory.go
  backend/app/usecase/auth/payload/payload.go
  backend/app/usecase/auth/payloadtest/factory_stub.go
  backend/app/usecase/auth/payloadtest/payload_stub.go
Labels: size/L

#615 Add reusable table component
  frontend/src/component/styles/color.scss
  frontend/src/component/ui/Table.scss
  frontend/src/component/ui/Table.spec.tsx
  frontend/src/component/ui/Table.tsx
Labels: enhancement, size/L

#621 Rename toastRef to tableRef in table unit tests
  frontend/src/component/ui/Table.spec.tsx
Labels: bug, size/M

#622 Fix changelog tests
  backend/app/adapter/db/changelog.go
  backend/app/adapter/db/changelog_integration_test.go
Labels: Go, bug, size/S

#626 Fix styling leaking issue for Button component
  frontend/src/component/ui/Button.scss
  frontend/src/component/ui/Button.tsx
Labels: enhancement, size/XS

#627 Fix table header not filling background with change in header width
  frontend/src/component/ui/Table.scss
Labels: bug, size/XS

#633 Add basic page control component
  frontend/src/component/styles/color.scss
  frontend/src/component/styles/shape.scss
  frontend/src/component/ui/PageControl.scss
  frontend/src/component/ui/PageControl.spec.tsx
  frontend/src/component/ui/PageControl.tsx
Labels: size/L

#630 Add GetURLs method to url usecase
  backend/app/adapter/db/url.go
  backend/app/adapter/graphql/graphql_test.go
  backend/app/adapter/graphql/resolver/authquery_test.go
  backend/app/adapter/graphql/resolver/query_test.go
  backend/app/usecase/repository/url_fake.go
  backend/app/usecase/url/urlretriever.go
  backend/app/usecase/url/urlretriever_test.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: Go, enhancement, size/L

#635 Fix test cases referencing incorrect variable when running
  backend/app/usecase/url/urlretriever_test.go
Labels: Go, bug, size/XS

#636 Remove unused captcha service from Home page component
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/Home.tsx
  frontend/src/dep.ts
Labels: maintainability, size/XS

#637 Add meaningful error message for invalid recaptcha site key
  frontend/src/service/Captcha.service.ts
  frontend/src/service/Error.service.ts
  frontend/src/service/Url.service.ts
Labels: size/M

#638 Promote sign in after auth token expired
  backend/app/adapter/graphql/resolver/authmutation.go
  backend/app/adapter/graphql/resolver/authquery.go
  backend/app/adapter/graphql/resolver/authquery_test.go
  backend/app/adapter/graphql/resolver/error.go
  backend/app/adapter/graphql/resolver/mutation.go
  backend/app/adapter/graphql/resolver/query.go
  backend/app/adapter/graphql/resolver/query_test.go
  backend/app/adapter/graphql/resolver/viewer.go
  frontend/src/component/pages/Home.tsx
  frontend/src/service/Captcha.service.ts
  frontend/src/service/Error.service.ts
  frontend/src/service/Url.service.ts
Labels: bug, size/L

#639 deploy
  .drone.yml
  backend/app/adapter/db/changelog.go
  backend/app/adapter/db/changelog_integration_test.go
  backend/app/adapter/db/url.go
  backend/app/adapter/graphql/graphql.go
  backend/app/adapter/graphql/graphql_test.go
  backend/app/adapter/graphql/resolver/authmutation.go
  backend/app/adapter/graphql/resolver/authquery.go
  backend/app/adapter/graphql/resolver/authquery_test.go
  backend/app/adapter/graphql/resolver/change.go
  backend/app/adapter/graphql/resolver/changelog.go
  backend/app/adapter/graphql/resolver/error.go
  backend/app/adapter/graphql/resolver/mutation.go
  backend/app/adapter/graphql/resolver/query.go
  backend/app/adapter/graphql/resolver/query_test.go
  backend/app/adapter/graphql/resolver/resolver.go
  backend/app/adapter/graphql/resolver/viewer.go
  backend/app/adapter/graphql/schema.go
  backend/app/entity/change.go
  backend/app/usecase/auth/payload/email.go
  backend/app/usecase/auth/payload/email_test.go
  backend/app/usecase/auth/payload/factory.go
  backend/app/usecase/auth/payload/payload.go
  backend/app/usecase/auth/payloadtest/factory_stub.go
  backend/app/usecase/auth/payloadtest/payload_stub.go
  backend/app/usecase/changelog/changelog.go
  backend/app/usecase/changelog/changelog_test.go
  backend/app/usecase/repository/url_fake.go
  backend/app/usecase/url/urlretriever.go
  backend/app/usecase/url/urlretriever_test.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  frontend/.env.testing
  frontend/package.json
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/Home.tsx
  frontend/src/component/styles/color.scss
  frontend/src/component/styles/shape.scss
  frontend/src/component/ui/Button.scss
  frontend/src/component/ui/Button.tsx
  frontend/src/component/ui/PageControl.scss
  frontend/src/component/ui/PageControl.spec.tsx
  frontend/src/component/ui/PageControl.tsx
  frontend/src/component/ui/Table.scss
  frontend/src/component/ui/Table.spec.tsx
  frontend/src/component/ui/Table.tsx
  frontend/src/dep.ts
  frontend/src/service/Captcha.service.ts
  frontend/src/service/Error.service.ts
  frontend/src/service/Url.service.ts
Labels: size/XXL

#641 Extend auth token valid duration from a day to a week
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: size/S

#642 deploy
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: size/S

#648 Rename GetURLs to GetURLsByUser in url usecase
  backend/app/usecase/url/urlretriever.go
  backend/app/usecase/url/urlretriever_test.go
  backend/dep/wire_gen.go
Labels: Go, enhancement, size/M

#652 Add GraphQL API to show URLs created by current user
  backend/app/adapter/graphql/resolver/authquery.go
  backend/app/adapter/graphql/schema.go
Labels: Go, enhancement, size/S

#650 Automate env config parsing with reflection
  backend/envconfig/envconfig.go
  backend/envconfig/envconfig_test.go
  backend/main.go
Labels: size/L

#655 Create unit package
  backend/unit/unit.go
  backend/unit/unit_test.go
Labels: Go, size/L

#662 Refrain PageControl mount from triggering onPageChanged event
  frontend/src/component/ui/PageControl.tsx
Labels: bug, size/XS

#656 Add UserChangeLog respository
  backend/app/adapter/db/migration/13_create_user_changelog_table.sql
  backend/app/adapter/db/table/user_changelog.go
  backend/app/adapter/db/user_changelog.go
  backend/app/adapter/db/user_changelog_integration_test.go
  backend/app/usecase/repository/user_changelog.go
Labels: Go, enhancement, size/L

#664 Fix memory leak warning in toast unit tests
  frontend/src/component/ui/Toast.spec.tsx
Labels: bug, size/XS

#665 Replace hard-coded auth token valid duration with value from env variable
  README.md
  backend/.env.dist
  backend/app/app.go
  backend/cmd/cmd.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/envconfig/envconfig.go
  backend/envconfig/envconfig_test.go
  backend/main.go
Labels: Go, size/L

#660 Add UserShortLinkSection component
  frontend/src/component/pages/shared/UserShortLinksSection.spec.tsx
  frontend/src/component/pages/shared/UserShortLinksSection.tsx
  frontend/src/service/ShortLink.service.ts
Labels: React, enhancement, size/L

#666 Switch from local logger to Datadog
  README.md
  backend/.env.dist
  backend/app/app.go
  backend/cmd/cmd.go
  backend/dep/provider/datadog.go
  backend/dep/provider/logger.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
  backend/main.go
Labels: size/L

#667 deploy
  README.md
  backend/.env.dist
  backend/app/adapter/db/migration/13_create_user_changelog_table.sql
  backend/app/adapter/db/table/user_changelog.go
  backend/app/adapter/db/user_changelog.go
  backend/app/adapter/db/user_changelog_integration_test.go
  backend/app/adapter/graphql/resolver/authquery.go
  backend/app/adapter/graphql/schema.go
  backend/app/app.go
  backend/app/usecase/repository/user_changelog.go
  backend/app/usecase/url/urlretriever.go
  backend/app/usecase/url/urlretriever_test.go
  backend/cmd/cmd.go
  backend/dep/provider/datadog.go
  backend/dep/provider/logger.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/envconfig/envconfig.go
  backend/envconfig/envconfig_test.go
  backend/go.mod
  backend/go.sum
  backend/main.go
  backend/unit/unit.go
  backend/unit/unit_test.go
  frontend/src/component/pages/shared/UserShortLinksSection.spec.tsx
  frontend/src/component/pages/shared/UserShortLinksSection.tsx
  frontend/src/component/ui/PageControl.tsx
  frontend/src/component/ui/Toast.spec.tsx
  frontend/src/service/ShortLink.service.ts
Labels: size/XXL

#668 Collect LongLinkRetrieval metrics
  backend/app/adapter/instrumentation/factory.go
  backend/app/adapter/instrumentation/instrumentation.go
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
  backend/app/app.go
  backend/app/usecase/observability/obervability.go
  backend/dep/provider/datadog.go
  backend/dep/provider/routes.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
Labels: size/L

#669 deploy
  backend/app/adapter/instrumentation/factory.go
  backend/app/adapter/instrumentation/instrumentation.go
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
  backend/app/app.go
  backend/app/usecase/observability/obervability.go
  backend/dep/provider/datadog.go
  backend/dep/provider/routes.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
Labels: size/L

#670 Track interaction and coarse geo location of the anonymous user
  README.md
  backend/.env.dist
  backend/app/adapter/instrumentation/factory.go
  backend/app/adapter/instrumentation/instrumentation.go
  backend/app/adapter/routing/handle.go
  backend/app/app.go
  backend/app/usecase/observability/obervability.go
  backend/cmd/cmd.go
  backend/dep/provider/ipstack.go
  backend/dep/provider/segment.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
  backend/main.go
Labels: size/L

#671 Add debugging info
  backend/app/adapter/instrumentation/factory.go
Labels: size/XS

#672 deploy
  README.md
  backend/.env.dist
  backend/app/adapter/instrumentation/factory.go
  backend/app/adapter/instrumentation/instrumentation.go
  backend/app/adapter/routing/handle.go
  backend/app/app.go
  backend/app/usecase/observability/obervability.go
  backend/cmd/cmd.go
  backend/dep/provider/ipstack.go
  backend/dep/provider/segment.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
  backend/main.go
Labels: size/L

#675 Replace Apollo with custom GraphQL client
  frontend/package.json
  frontend/src/dep.ts
  frontend/src/graphql/error.ts
  frontend/src/service/GraphQL.service.ts
  frontend/src/service/HTTP.service.ts
  frontend/src/service/Url.service.ts
  frontend/yarn.lock
Labels: maintainability, size/L

#676 Extract real client IP in URL redirect request
  backend/app/adapter/instrumentation/factory.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
Labels: size/S

#677 Use the latest version of kgs and app framework
  backend/go.mod
  backend/go.sum
Labels: size/XS

#678 deploy
  backend/app/adapter/instrumentation/factory.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
  frontend/package.json
  frontend/src/dep.ts
  frontend/src/graphql/error.ts
  frontend/src/service/GraphQL.service.ts
  frontend/src/service/HTTP.service.ts
  frontend/src/service/Url.service.ts
  frontend/yarn.lock
Labels: size/L

#679 Refactor instrumentation code
  backend/app/adapter/instrumentation/factory.go
  backend/app/adapter/instrumentation/instrumentation.go
  backend/app/adapter/request/client.go
  backend/app/adapter/request/instrumentation.go
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
  backend/app/usecase/instrumentation/instrumentation.go
  backend/dep/provider/routes.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: size/L

#680 Add feature toggle repository
  backend/app/adapter/db/bool.go
  backend/app/adapter/db/featuretoggle.go
  backend/app/adapter/db/featuretoggle_test.go
  backend/app/adapter/db/migration/14_create_feature_toggle_table.sql
  backend/app/adapter/db/table/featuretoggle.go
  backend/app/entity/toggle.go
  backend/app/usecase/repository/featuretoggle.go
Labels: size/L

#682 Add arberiii and rohithbalaji123 as code owners
  .github/CODEOWNERS
Labels: size/S

#681 Add ErrEntryNotFound to UserChangeLog repository
  backend/app/adapter/db/user_changelog.go
  backend/app/usecase/repository/user_changelog.go
Labels: Go, enhancement, size/S

#683 Return authentication error in change log API
  backend/app/adapter/graphql/resolver/authquery.go
Labels: Go, size/XS

#685 Add feature decision use case
  backend/app/usecase/feature/decision.go
  backend/app/usecase/feature/decision_test.go
  backend/app/usecase/instrumentation/instrumentation.go
  backend/app/usecase/repository/featuretoggle_fake.go
  backend/go.mod
  backend/go.sum
Labels: size/L

#674 Add ShortLink Sevice
  frontend/src/service/ShortGraphQLApiService.ts
  frontend/src/service/ShortLink.service.ts
Labels: React, enhancement, size/L

#686 Add feature toggle API
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
  backend/dep/provider/routes.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: enhancement, size/M

#687 deploy
  .github/CODEOWNERS
  backend/app/adapter/db/bool.go
  backend/app/adapter/db/featuretoggle.go
  backend/app/adapter/db/featuretoggle_test.go
  backend/app/adapter/db/migration/14_create_feature_toggle_table.sql
  backend/app/adapter/db/table/featuretoggle.go
  backend/app/adapter/db/user_changelog.go
  backend/app/adapter/graphql/resolver/authquery.go
  backend/app/adapter/instrumentation/factory.go
  backend/app/adapter/instrumentation/instrumentation.go
  backend/app/adapter/request/client.go
  backend/app/adapter/request/instrumentation.go
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
  backend/app/entity/toggle.go
  backend/app/usecase/feature/decision.go
  backend/app/usecase/feature/decision_test.go
  backend/app/usecase/instrumentation/instrumentation.go
  backend/app/usecase/repository/featuretoggle.go
  backend/app/usecase/repository/featuretoggle_fake.go
  backend/app/usecase/repository/user_changelog.go
  backend/dep/provider/routes.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
  frontend/src/service/ShortGraphQLApiService.ts
  frontend/src/service/ShortLink.service.ts
Labels: size/XL

#688 Integrate feature toggle with UI
  frontend/src/component/UIFactory.tsx
  frontend/src/dep.ts
  frontend/src/service/FeatureDecision.service.ts
  frontend/src/service/GraphQL.service.ts
  frontend/src/service/HTTP.service.ts
  frontend/src/service/ShortGraphQL.api.ts
  frontend/src/service/ShortHTTP.api.ts
  frontend/src/service/ShortLink.service.ts
  frontend/src/service/StaticConfigDecision.service.ts
  frontend/src/service/feature-decision/DynamicDecision.service.ts
  frontend/src/service/feature-decision/FeatureDecision.service.ts
  frontend/src/service/feature-decision/StaticConfigDecision.service.ts
Labels: size/L

#689 Change instrumentation requests to async
  backend/app/adapter/request/instrumentation.go
  backend/app/usecase/feature/decision_test.go
  backend/app/usecase/instrumentation/instrumentation.go
Labels: size/L

#690 Cache feature toggle response in the memory
  frontend/src/dep.ts
  frontend/src/service/cache/cache.ts
  frontend/src/service/cache/in-memory.cache.ts
  frontend/src/service/feature-decision/DynamicDecision.service.ts
Labels: size/M

#691 deploy
  backend/app/adapter/request/instrumentation.go
  backend/app/usecase/feature/decision_test.go
  backend/app/usecase/instrumentation/instrumentation.go
  frontend/src/component/UIFactory.tsx
  frontend/src/dep.ts
  frontend/src/service/FeatureDecision.service.ts
  frontend/src/service/GraphQL.service.ts
  frontend/src/service/HTTP.service.ts
  frontend/src/service/ShortGraphQL.api.ts
  frontend/src/service/ShortHTTP.api.ts
  frontend/src/service/ShortLink.service.ts
  frontend/src/service/StaticConfigDecision.service.ts
  frontend/src/service/cache/cache.ts
  frontend/src/service/cache/in-memory.cache.ts
  frontend/src/service/feature-decision/DynamicDecision.service.ts
  frontend/src/service/feature-decision/FeatureDecision.service.ts
  frontend/src/service/feature-decision/StaticConfigDecision.service.ts
Labels: size/L

#692 Add issue template for refactor
  .github/ISSUE_TEMPLATE/refactor.md
Labels: size/S

#693 Fix component state automatic reset bug
  frontend/src/component/UIFactory.tsx
  frontend/src/dep.ts
  frontend/src/service/feature-decision/DynamicDecision.service.ts
  frontend/src/service/feature-decision/FeatureDecision.service.ts
  frontend/src/service/feature-decision/StaticConfigDecision.service.ts
Labels: size/L

#694 Integrate user short links section into home page
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/Home.tsx
  frontend/src/dep.ts
  frontend/src/service/ShortGraphQL.api.ts
  frontend/src/service/ShortLink.service.ts
  frontend/src/service/feature-decision/DynamicDecision.service.ts
  frontend/src/service/feature-decision/FeatureDecision.service.ts
  frontend/src/state/actions.ts
  frontend/src/state/reducers.ts
Labels: enhancement, size/L

#697 Retyle user short links section
  frontend/src/component/pages/Home.scss
  frontend/src/component/pages/Home.tsx
  frontend/src/component/pages/shared/UserShortLinksSection.scss
  frontend/src/component/pages/shared/UserShortLinksSection.spec.tsx
  frontend/src/component/pages/shared/UserShortLinksSection.tsx
  frontend/src/component/ui/Table.scss
Labels: size/L

#699 deploy
  .github/ISSUE_TEMPLATE/refactor.md
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/Home.scss
  frontend/src/component/pages/Home.tsx
  frontend/src/component/pages/shared/UserShortLinksSection.scss
  frontend/src/component/pages/shared/UserShortLinksSection.spec.tsx
  frontend/src/component/pages/shared/UserShortLinksSection.tsx
  frontend/src/component/ui/Table.scss
  frontend/src/dep.ts
  frontend/src/service/ShortGraphQL.api.ts
  frontend/src/service/ShortLink.service.ts
  frontend/src/service/feature-decision/DynamicDecision.service.ts
  frontend/src/service/feature-decision/FeatureDecision.service.ts
  frontend/src/service/feature-decision/StaticConfigDecision.service.ts
  frontend/src/state/actions.ts
  frontend/src/state/reducers.ts
Labels: size/L

#700 Break long link into multiple lines
  frontend/src/component/pages/shared/UserShortLinksSection.scss
  frontend/src/component/pages/shared/UserShortLinksSection.tsx
Labels: size/S

#701 deploy
  frontend/src/component/pages/shared/UserShortLinksSection.scss
  frontend/src/component/pages/shared/UserShortLinksSection.tsx
Labels: size/S

#703 Fix empty user ID for instrumentation
  backend/app/usecase/instrumentation/instrumentation.go
Labels: size/M

#704 deploy
  backend/app/usecase/instrumentation/instrumentation.go
Labels: size/M

#706 Rename auth package to authenticator
  backend/app/adapter/graphql/graphql.go
  backend/app/adapter/graphql/graphql_test.go
  backend/app/adapter/graphql/resolver/authmutation.go
  backend/app/adapter/graphql/resolver/authquery.go
  backend/app/adapter/graphql/resolver/authquery_test.go
  backend/app/adapter/graphql/resolver/mutation.go
  backend/app/adapter/graphql/resolver/query.go
  backend/app/adapter/graphql/resolver/query_test.go
  backend/app/adapter/graphql/resolver/resolver.go
  backend/app/adapter/graphql/resolver/viewer.go
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
  backend/app/usecase/authenticator/authenticator.go
  backend/app/usecase/authenticator/authenticator_fake.go
  backend/app/usecase/authenticator/authenticator_test.go
  backend/app/usecase/authenticator/payload.go
  backend/app/usecase/authenticator/payload/email.go
  backend/app/usecase/authenticator/payload/email_test.go
  backend/app/usecase/authenticator/payload/factory.go
  backend/app/usecase/authenticator/payload/payload.go
  backend/app/usecase/authenticator/payloadtest/factory_stub.go
  backend/app/usecase/authenticator/payloadtest/payload_stub.go
  backend/app/usecase/sso/sso.go
  backend/app/usecase/sso/sso_test.go
  backend/dep/provider/authenticator.go
  backend/dep/provider/routes.go
Labels: maintainability

#708 Support switching to local logger under dev environment
  backend/dep/provider/entryrepo.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/env/env.go
Labels: size/M

#709 Switch from blocking to parallel
  backend/app/usecase/instrumentation/instrumentation.go
Labels: bug, size/S

#710 Remove unnecessary error logs when converting empty IP to geolocation
  backend/app/adapter/request/client.go
Labels: maintainability, size/XS

#712 Add static deature decision maker
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
  backend/app/usecase/feature/decision.go
  backend/app/usecase/feature/dynamic.go
  backend/app/usecase/feature/dynamic_test.go
  backend/app/usecase/feature/static.go
  backend/dep/provider/feature.go
  backend/dep/provider/routes.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: maintainability, size/L

#714 Show error for malicious content input
  frontend/src/service/Error.service.ts
Labels: React

#715 Replace ID of anonymous user with hard-coded value
  backend/app/adapter/routing/handle.go
  backend/app/usecase/instrumentation/instrumentation.go
Labels: enhancement, size/M

#716 deploy
  backend/app/adapter/routing/handle.go
  backend/app/usecase/instrumentation/instrumentation.go
  frontend/src/service/Error.service.ts
Labels: size/M

#696 Add feature update existing urls to db adapter
  backend/app/adapter/db/url.go
  backend/app/adapter/db/url_integration_test.go
  backend/app/adapter/db/userurl.go
  backend/app/usecase/repository/url.go
  backend/app/usecase/repository/url_fake.go
Labels: Go, size/L

#718 Track when a short link is created
  backend/app/adapter/graphql/graphql_test.go
  backend/app/usecase/url/urlcreator.go
  backend/app/usecase/url/urlcreator_test.go
  backend/dep/wire_gen.go
Labels: size/S

#719 Support malicious URL detection
  backend/.env.dist
  backend/app/adapter/google/safebrowsing.go
  backend/app/adapter/graphql/graphql_test.go
  backend/app/adapter/graphql/resolver/authmutation.go
  backend/app/adapter/graphql/resolver/error.go
  backend/app/app.go
  backend/app/usecase/risk/blacklist.go
  backend/app/usecase/risk/blacklist_fake.go
  backend/app/usecase/risk/risk.go
  backend/app/usecase/url/urlcreator.go
  backend/app/usecase/url/urlcreator_test.go
  backend/dep/provider/google.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/main.go
Labels: size/L

#720 Fix malicious URL detection bug
  backend/app/adapter/google/safebrowsing.go
Labels: size/XS

#721 deploy
  backend/.env.dist
  backend/app/adapter/db/url.go
  backend/app/adapter/db/url_integration_test.go
  backend/app/adapter/db/userurl.go
  backend/app/adapter/google/safebrowsing.go
  backend/app/adapter/graphql/graphql_test.go
  backend/app/adapter/graphql/resolver/authmutation.go
  backend/app/adapter/graphql/resolver/error.go
  backend/app/app.go
  backend/app/usecase/repository/url.go
  backend/app/usecase/repository/url_fake.go
  backend/app/usecase/risk/blacklist.go
  backend/app/usecase/risk/blacklist_fake.go
  backend/app/usecase/risk/risk.go
  backend/app/usecase/url/urlcreator.go
  backend/app/usecase/url/urlcreator_test.go
  backend/dep/provider/google.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/main.go
Labels: size/L

#723 [Refactor] Move envconfig into app framework
  backend/envconfig/envconfig.go
  backend/envconfig/envconfig_test.go
  backend/go.mod
  backend/go.sum
  backend/main.go
  backend/unit/unit.go
  backend/unit/unit_test.go
Labels: size/XL
