Repository short-d/short, pull requests merged in 2020-07, with the labels that each got.

#916 Support having options in Section
  frontend/src/component/ui/Section.scss
  frontend/src/component/ui/Section.spec.tsx
  frontend/src/component/ui/Section.tsx
Labels: size/M

#915 Revise contributing guidance
  CONTRIBUTING.md
Labels: documentation, size/M

#917 Update links in README
  README.md
Labels: documentation, size/S

#918 Add app repository
  backend/app/adapter/sqldb/app.go
  backend/app/adapter/sqldb/app_integration_test.go
  backend/app/adapter/sqldb/migration/27_add_app_table.sql
  backend/app/adapter/sqldb/table/app.go
  backend/app/entity/app.go
  backend/app/usecase/repository/app.go
  backend/app/usecase/repository/app_fake.go
Labels: size/L

#919 Handle duplicated alias in Usecase
  backend/app/adapter/gqlapi/api_test.go
  backend/app/usecase/shortlink/updater.go
  backend/app/usecase/shortlink/updater_test.go
Labels: bug, size/M

#920 Refactor error type checking to use errors.As
  backend/app/adapter/gqlapi/resolver/authmutation.go
  backend/app/usecase/changelog/changelog.go
  backend/app/usecase/shortlink/updater_test.go
Labels: size/M

#923 Add test cases for usecase/shortlink
  backend/app/usecase/shortlink/creator_test.go
  backend/app/usecase/shortlink/metatag_test.go
  backend/app/usecase/shortlink/retriever_test.go
Labels: Go, maintainability, size/M

#921 Fix and add test cases for short link updater
  backend/app/usecase/shortlink/updater_test.go
Labels: bug, size/M

#924 Fix long link auto fill in bug
  frontend/src/component/form/TextField.tsx
  frontend/src/component/pages/HomePage.tsx
  frontend/src/component/pages/shared/CreateShortLinkSection.tsx
  frontend/src/state/actions.ts
  frontend/src/state/reducers.test.ts
  frontend/src/state/reducers.ts
Labels: size/XL

#925 deploy
  CONTRIBUTING.md
  README.md
  backend/.env.dist
  backend/Dockerfile
  backend/app/adapter/gqlapi/api.go
  backend/app/adapter/gqlapi/api_test.go
  backend/app/adapter/gqlapi/resolver/authmutation.go
  backend/app/adapter/gqlapi/schema.go
  backend/app/adapter/gqlapi/schema.graphql
  backend/app/adapter/sqldb/app.go
  backend/app/adapter/sqldb/app_integration_test.go
  backend/app/adapter/sqldb/migration/27_add_app_table.sql
  backend/app/adapter/sqldb/table/app.go
  backend/app/app.go
  backend/app/entity/app.go
  backend/app/fw/filesystem/filesystem.go
  backend/app/fw/filesystem/local.go
  backend/app/usecase/changelog/changelog.go
  backend/app/usecase/repository/app.go
  backend/app/usecase/repository/app_fake.go
  backend/app/usecase/shortlink/creator_test.go
  backend/app/usecase/shortlink/metatag_test.go
  backend/app/usecase/shortlink/retriever_test.go
  backend/app/usecase/shortlink/updater.go
  backend/app/usecase/shortlink/updater_test.go
  backend/dep/provider/graphql.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.sum
  backend/main.go
  frontend/src/component/form/TextField.tsx
  frontend/src/component/pages/HomePage.tsx
  frontend/src/component/pages/shared/CreateShortLinkSection.tsx
  frontend/src/component/ui/Section.scss
  frontend/src/component/ui/Section.spec.tsx
  frontend/src/component/ui/Section.tsx
  frontend/src/service/Captcha.service.ts
  frontend/src/service/ChangeLog.service.ts
  frontend/src/service/shortGraphQL/ChangeLogGraphQL.api.ts
  frontend/src/service/shortGraphQL/schema.ts
  frontend/src/state/actions.ts
  frontend/src/state/reducers.test.ts
  frontend/src/state/reducers.ts
  widget/emotic/README.md
Labels: size/XXL

#926 Add ApiKey repository
  backend/app/adapter/sqldb/apikey.go
  backend/app/adapter/sqldb/apikey_integration_test.go
  backend/app/adapter/sqldb/migration/28_add_api_key_table.sql
  backend/app/adapter/sqldb/table/apikey.go
  backend/app/entity/apikey.go
  backend/app/usecase/repository/apikey.go
  backend/app/usecase/repository/apikey_fake.go
  backend/app/usecase/repository/error.go
Labels: size/L

#894 Implement gRPC API for Social Media Sharing Customization
  backend/app/adapter/grpcapi/api.go
  backend/app/adapter/grpcapi/metatag.go
  backend/app/adapter/grpcapi/proto/metatag.pb.go
  backend/app/adapter/grpcapi/proto/metatag.proto
  backend/go.mod
  backend/scripts/proto
Labels: Go, enhancement, size/XL

#932 Support markdown viewer for change logs
  frontend/package.json
  frontend/src/component/styles/color.scss
  frontend/src/component/ui/ChangeLogModal.scss
  frontend/src/component/ui/ChangeLogModal.tsx
  frontend/src/component/ui/MarkdownViewer.scss
  frontend/src/component/ui/MarkdownViewer.tsx
  frontend/yarn.lock
Labels: enhancement, size/M

#928 Provide fake reCaptcha verifier in dev
  backend/app/adapter/gqlapi/api_test.go
  backend/app/usecase/requester/verifier.go
  backend/app/usecase/requester/verifier_fake.go
  backend/app/usecase/requester/verifier_recaptcha.go
  backend/dep/provider/verifier.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: size/M

#933 Support default delay duration for toast messages
  frontend/src/component/pages/HomePage.tsx
  frontend/src/component/ui/Toast.spec.tsx
  frontend/src/component/ui/Toast.tsx
Labels: enhancement, size/M

#937 Disallow special URL characters as aliases
  backend/app/usecase/validator/alias.go
  backend/app/usecase/validator/alias_test.go
Labels: Go, size/S

#930 Add incident and progress DB table
  backend/app/adapter/sqldb/migration/29_create_incident_table.sql
  backend/app/adapter/sqldb/migration/30_create_progress_table.sql
  backend/app/adapter/sqldb/table/incident.go
  backend/app/adapter/sqldb/table/progress.go
Labels: size/M

#939 Migrate to CSS module to avoid style leaking
  frontend/src/component/ui/Button.module.scss
  frontend/src/component/ui/Button.tsx
Labels: enhancement, maintainability, size/XS

#940 Support styling for button
  frontend/src/component/pages/shared/sign-in/FacebookSignInButton.tsx
  frontend/src/component/pages/shared/sign-in/GithubSignInButton.tsx
  frontend/src/component/pages/shared/sign-in/GoogleSignInButton.tsx
  frontend/src/component/pages/shared/sign-in/SignInButton.scss
  frontend/src/component/pages/shared/sign-in/SignInButton.tsx
  frontend/src/component/ui/Button.module.scss
  frontend/src/component/ui/Button.tsx
  frontend/src/component/ui/styling.ts
Labels: maintainability, size/M

#941 Add documentation on launching emotic dev server
  widget/emotic/README.md
Labels: size/S

#942 Add Storybook to organize UI component
  story/.gitignore
  story/.prettierrc
  story/.storybook/main.js
  story/package-lock.json
  story/package.json
  story/src/typings.d.ts
  story/tsconfig.json
  story/yarn.lock
Labels: maintainability

#943 Create story for button
  story/.storybook/main.js
  story/package.json
  story/src/0-Button.stories.module.scss
  story/src/0-Button.stories.tsx
  story/tsconfig.json
  story/yarn.lock
Labels: size/L

#944 Add continuous deployment for storybook
  .drone.yml
  story/.dockerignore
  story/Dockerfile
  story/default.conf
  story/package.json
Labels: size/M

#946 Revert "Add continuous deployment for storybook"
  .drone.yml
  story/.dockerignore
  story/Dockerfile
  story/default.conf
  story/package.json
Labels: size/M

#947 Add continuous deployment for storybook
  .drone.yml
  .gitignore
  story/.dockerignore
  story/.gitignore
  story/Dockerfile
  story/build/favicon.ico
  story/build/iframe.html
  story/build/index.html
  story/build/lib/frontend/src/component/ui/Button.d.ts
  story/build/lib/frontend/src/component/ui/styling.d.ts
  story/build/lib/story/src/0-Button.stories.d.ts
  story/build/main.9afa205c746a1461254d.bundle.js
  story/build/main.c0a2c739a1da0629dcbd.bundle.js
  story/build/main.c0a2c739a1da0629dcbd.bundle.js.map
  story/build/runtime~main.286b69a873d49f2f199c.bundle.js
  story/build/runtime~main.c0a2c739a1da0629dcbd.bundle.js
  story/build/runtime~main.c0a2c739a1da0629dcbd.bundle.js.map
  story/build/sb_dll/storybook_ui-manifest.json
  story/build/sb_dll/storybook_ui_dll.LICENCE
  story/build/sb_dll/storybook_ui_dll.js
  story/build/vendors~main.8491b114bd756e671c7d.bundle.js
  story/build/vendors~main.c0a2c739a1da0629dcbd.bundle.js
  story/build/vendors~main.c0a2c739a1da0629dcbd.bundle.js.LICENSE.txt
  story/build/vendors~main.c0a2c739a1da0629dcbd.bundle.js.map
  story/default.conf
  story/package.json
Labels: documentation, maintainability

#949 Fix Docker image name
  .drone.yml
Labels: bug, size/XS

#951 deploy
  .drone.yml
Labels: size/XS

#952 Fix image spelling
  .drone.yml
Labels: bug, size/XS

#953 deploy
  .drone.yml
Labels: size/XS

#955 Dynamically build storybook
  .drone.yml
  story/.gitignore
  story/build/favicon.ico
  story/build/iframe.html
  story/build/index.html
  story/build/lib/frontend/src/component/ui/Button.d.ts
  story/build/lib/frontend/src/component/ui/styling.d.ts
  story/build/lib/story/src/0-Button.stories.d.ts
  story/build/main.9afa205c746a1461254d.bundle.js
  story/build/main.c0a2c739a1da0629dcbd.bundle.js
  story/build/main.c0a2c739a1da0629dcbd.bundle.js.map
  story/build/runtime~main.286b69a873d49f2f199c.bundle.js
  story/build/runtime~main.c0a2c739a1da0629dcbd.bundle.js
  story/build/runtime~main.c0a2c739a1da0629dcbd.bundle.js.map
  story/build/sb_dll/storybook_ui-manifest.json
  story/build/sb_dll/storybook_ui_dll.LICENCE
  story/build/sb_dll/storybook_ui_dll.js
  story/build/vendors~main.8491b114bd756e671c7d.bundle.js
  story/build/vendors~main.c0a2c739a1da0629dcbd.bundle.js
  story/build/vendors~main.c0a2c739a1da0629dcbd.bundle.js.LICENSE.txt
  story/build/vendors~main.c0a2c739a1da0629dcbd.bundle.js.map
  story/package-lock.json
Labels: maintainability

#935 Add create change section
  frontend/src/component/pages/admin/changelog/CreateChangeSection.scss
  frontend/src/component/pages/admin/changelog/CreateChangeSection.tsx
  frontend/src/component/styles/color.scss
  frontend/src/component/ui/Button.module.scss
  frontend/src/state/actions.ts
  frontend/src/state/reducers.ts
Labels: enhancement, size/L

#938 Move business logic for short link out of resolver
  backend/app/adapter/gqlapi/api_test.go
  backend/app/adapter/gqlapi/input/shortlink.go
  backend/app/adapter/gqlapi/resolver/authmutation.go
  backend/app/adapter/gqlapi/resolver/authquery_test.go
  backend/app/adapter/gqlapi/resolver/error.go
  backend/app/adapter/gqlapi/resolver/query_test.go
  backend/app/adapter/sqldb/short_link.go
  backend/app/adapter/sqldb/short_link_integration_test.go
  backend/app/adapter/sqldb/user_short_link.go
  backend/app/entity/shortlink.go
  backend/app/fw/ptr/string.go
  backend/app/usecase/repository/shortlink.go
  backend/app/usecase/repository/shortlink_fake.go
  backend/app/usecase/repository/usershortlink.go
  backend/app/usecase/repository/usershortlink_fake.go
  backend/app/usecase/search/search_test.go
  backend/app/usecase/shortlink/creator.go
  backend/app/usecase/shortlink/creator_test.go
  backend/app/usecase/shortlink/metatag_test.go
  backend/app/usecase/shortlink/retriever_test.go
  backend/app/usecase/shortlink/updater.go
  backend/app/usecase/shortlink/updater_test.go
  backend/app/usecase/validator/alias.go
  backend/app/usecase/validator/alias_test.go
  backend/app/usecase/validator/longlink.go
  backend/app/usecase/validator/longlink_test.go
  backend/app/usecase/validator/validator.go
Labels: size/XXL

#961 deploy
  backend/app/adapter/gqlapi/api_test.go
  backend/app/adapter/gqlapi/input/shortlink.go
  backend/app/adapter/gqlapi/resolver/authmutation.go
  backend/app/adapter/gqlapi/resolver/authquery_test.go
  backend/app/adapter/gqlapi/resolver/error.go
  backend/app/adapter/gqlapi/resolver/query_test.go
  backend/app/adapter/sqldb/short_link.go
  backend/app/adapter/sqldb/short_link_integration_test.go
  backend/app/adapter/sqldb/user_short_link.go
  backend/app/entity/shortlink.go
  backend/app/fw/ptr/string.go
  backend/app/usecase/repository/shortlink.go
  backend/app/usecase/repository/shortlink_fake.go
  backend/app/usecase/repository/usershortlink.go
  backend/app/usecase/repository/usershortlink_fake.go
  backend/app/usecase/search/search_test.go
  backend/app/usecase/shortlink/creator.go
  backend/app/usecase/shortlink/creator_test.go
  backend/app/usecase/shortlink/metatag_test.go
  backend/app/usecase/shortlink/retriever_test.go
  backend/app/usecase/shortlink/updater.go
  backend/app/usecase/shortlink/updater_test.go
  backend/app/usecase/validator/alias.go
  backend/app/usecase/validator/alias_test.go
  backend/app/usecase/validator/longlink.go
  backend/app/usecase/validator/longlink_test.go
  backend/app/usecase/validator/validator.go
  frontend/src/component/pages/admin/changelog/CreateChangeSection.scss
  frontend/src/component/pages/admin/changelog/CreateChangeSection.tsx
  frontend/src/component/styles/color.scss
  frontend/src/component/ui/Button.module.scss
  frontend/src/state/actions.ts
  frontend/src/state/reducers.ts
Labels: size/XXL

#962 Change Toggle SCSS to utilize CSS modules
  frontend/src/component/ui/Toggle.module.scss
  frontend/src/component/ui/Toggle.tsx
Labels: maintainability

#964 Inject gRPC service
  backend/.env.dist
  backend/app/adapter/grpcapi/api.go
  backend/app/app.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/main.go
Labels: Go, enhancement, size/L

#966 Add storybook for Toggle
  story/src/1-Toggle.stories.tsx
Labels: size/S

#968 Fix bug not showing created long link
  frontend/src/component/pages/shared/CreateShortLinkSection.tsx
Labels: bug, size/XS

#936 Add manage change logs sections
  frontend/src/component/pages/admin/changelog/ChangeLogTab.module.scss
  frontend/src/component/pages/admin/changelog/ChangeLogTab.tsx
  frontend/src/component/pages/admin/changelog/CreateChangeModal.module.scss
  frontend/src/component/pages/admin/changelog/CreateChangeModal.tsx
Labels: enhancement, size/L

#973 Extend Table component to support resizing and aligning items
  frontend/src/component/ui/Table.tsx
Labels: enhancement, size/M

#976 Refactor Icon component to use prop instead of states
  frontend/src/component/pages/AdminPage.tsx
  frontend/src/component/pages/admin/changelog/CreateChangeModal.tsx
  frontend/src/component/pages/shared/ErrorModal.tsx
  frontend/src/component/ui/ChangeLogModal.tsx
  frontend/src/component/ui/Icon.spec.tsx
  frontend/src/component/ui/Icon.tsx
  frontend/src/component/ui/SearchBar.tsx
Labels: refactor, size/M

#965 Add API key authenticator for third party app
  backend/app/fw/must/time.go
  backend/app/usecase/authenticator/credential.go
  backend/app/usecase/authenticator/payload/apikey.go
  backend/app/usecase/authenticator/thirdpartyapp.go
  backend/app/usecase/authenticator/thirdpartyapp_test.go
  backend/app/usecase/authorizer/authorizer.go
  backend/app/usecase/authorizer/rbac/permission/permission.go
  backend/app/usecase/authorizer/rbac/role/role.go
  backend/app/usecase/shortlink/updater_test.go
Labels: size/XL

#967 Added missing port info in the frontend link.
  frontend/src/service/Url.service.ts
Labels: size/XS

#978 Integrate listing and deleting changelogs in admin panel
  frontend/src/component/pages/admin/changelog/ChangeLogTab.module.scss
  frontend/src/component/pages/admin/changelog/ChangeLogTab.tsx
  frontend/src/component/pages/admin/changelog/ManageChangeLogsSection.module.scss
  frontend/src/component/pages/admin/changelog/ManageChangeLogsSection.tsx
  frontend/src/component/ui/Icon.tsx
  frontend/src/state/actions.ts
  frontend/src/state/reducers.ts
Labels: enhancement, size/L

#980 Replace mustParseTime with must.Time across the codebase
  backend/app/adapter/sqldb/app_integration_test.go
  backend/app/adapter/sqldb/main_test.go
  backend/app/adapter/sqldb/short_link_integration_test.go
  backend/app/adapter/sqldb/user_changelog_integration_test.go
  backend/app/adapter/sqldb/user_integration_test.go
  backend/app/adapter/sqldb/user_short_link_integration_test.go
  backend/app/fw/must/time.go
  backend/app/fw/ptr/time.go
Labels: Go, refactor, size/L

#981 deploy
  backend/app/adapter/sqldb/app_integration_test.go
  backend/app/adapter/sqldb/main_test.go
  backend/app/adapter/sqldb/short_link_integration_test.go
  backend/app/adapter/sqldb/user_changelog_integration_test.go
  backend/app/adapter/sqldb/user_integration_test.go
  backend/app/adapter/sqldb/user_short_link_integration_test.go
  backend/app/fw/must/time.go
  backend/app/fw/ptr/time.go
  frontend/src/component/pages/admin/changelog/ChangeLogTab.module.scss
  frontend/src/component/pages/admin/changelog/ChangeLogTab.tsx
  frontend/src/component/pages/admin/changelog/ManageChangeLogsSection.module.scss
  frontend/src/component/pages/admin/changelog/ManageChangeLogsSection.tsx
  frontend/src/component/ui/Icon.tsx
  frontend/src/service/Url.service.ts
  frontend/src/state/actions.ts
  frontend/src/state/reducers.ts
Labels: size/XL

#982 Rename URL into ShortLink in client side components
  frontend/src/component/App.tsx
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/HomePage.tsx
  frontend/src/component/pages/shared/CreateShortLinkSection.tsx
  frontend/src/component/pages/shared/Header.tsx
  frontend/src/component/pages/shared/UserShortLinksSection.tsx
  frontend/src/component/ui/SearchBar.tsx
  frontend/src/dep.ts
  frontend/src/entity/ShortLink.tsx
  frontend/src/service/Search.service.ts
  frontend/src/service/ShortLink.service.ts
  frontend/src/service/Url.service.ts
  frontend/src/service/shortGraphQL/ShortLinkGraphQL.api.ts
  frontend/src/state/reducers.ts
Labels: refactor, size/XL

#985 Refactor invokeCreateShortLinkApi
  frontend/src/dep.ts
  frontend/src/service/GraphQLError.ts
  frontend/src/service/ShortLink.service.ts
  frontend/src/service/shortGraphQL/ShortLinkGraphQL.api.ts
Labels: refactor, size/L

#986 Deploy
  frontend/src/component/App.tsx
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/HomePage.tsx
  frontend/src/component/pages/shared/CreateShortLinkSection.tsx
  frontend/src/component/pages/shared/Header.tsx
  frontend/src/component/pages/shared/UserShortLinksSection.tsx
  frontend/src/component/ui/SearchBar.tsx
  frontend/src/dep.ts
  frontend/src/entity/ShortLink.tsx
  frontend/src/service/GraphQLError.ts
  frontend/src/service/Search.service.ts
  frontend/src/service/ShortLink.service.ts
  frontend/src/service/Url.service.ts
  frontend/src/service/shortGraphQL/ShortLinkGraphQL.api.ts
  frontend/src/state/reducers.ts
Labels: size/L
