Repository short-d/short, pull requests merged in 2020-06, with the labels that each got.

#822 Remove Alex from code owners
  .github/CODEOWNERS
Labels: size/XS

#821 Fix failing integration tests
  backend/app/adapter/sqldb/facebooksso_integration_test.go
  backend/app/adapter/sqldb/featuretoggle_test.go
  backend/app/adapter/sqldb/githubsso_integration_test.go
  backend/app/adapter/sqldb/googlesso_integration_test.go
  backend/app/adapter/sqldb/migration/13_create_user_changelog_table.sql
  backend/app/adapter/sqldb/migration/16_switch_from_email_to_id.sql
  backend/app/adapter/sqldb/migration/19_add_constraints_to_user_changelog_table.sql
  backend/app/adapter/sqldb/migration/5_create_user_url_relation_table.sql
  backend/app/adapter/sqldb/short_link.go
  backend/app/adapter/sqldb/short_link_integration_test.go
  backend/app/adapter/sqldb/table/user_changelog.go
  backend/app/adapter/sqldb/user_changelog_integration_test.go
  backend/app/adapter/sqldb/user_short_link_integration_test.go
  backend/app/adapter/sqldb/userrole.go
  backend/app/adapter/sqldb/userrole_integration_test.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
  backend/scripts/integration-test
Labels: Go, size/L

#801 Add authorizer and include user for isFeatureEnable function
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
  backend/app/adapter/sqldb/facebooksso_integration_test.go
  backend/app/adapter/sqldb/githubsso_integration_test.go
  backend/app/adapter/sqldb/googlesso_integration_test.go
  backend/app/usecase/feature/checker.go
  backend/app/usecase/feature/decision.go
  backend/app/usecase/feature/dynamic.go
  backend/app/usecase/feature/dynamic_test.go
  backend/app/usecase/feature/static.go
  backend/dep/provider/feature.go
  backend/dep/provider/routes.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: enhancement, size/L

#772 Integrate admin panel
  frontend/src/component/App.tsx
  frontend/src/component/UIFactory.tsx
  frontend/src/dep.ts
  frontend/src/service/Auth.service.ts
  frontend/src/service/HTTP.service.ts
  frontend/src/service/ShortHTTP.api.ts
  frontend/src/service/feature-decision/DynamicDecision.service.ts
  frontend/src/service/feature-decision/FeatureDecision.service.ts
Labels: enhancement, size/M

#825 deploy
  .github/CODEOWNERS
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
  backend/app/adapter/sqldb/facebooksso_integration_test.go
  backend/app/adapter/sqldb/featuretoggle_test.go
  backend/app/adapter/sqldb/githubsso_integration_test.go
  backend/app/adapter/sqldb/googlesso_integration_test.go
  backend/app/adapter/sqldb/migration/13_create_user_changelog_table.sql
  backend/app/adapter/sqldb/migration/16_switch_from_email_to_id.sql
  backend/app/adapter/sqldb/migration/19_add_constraints_to_user_changelog_table.sql
  backend/app/adapter/sqldb/migration/5_create_user_url_relation_table.sql
  backend/app/adapter/sqldb/short_link.go
  backend/app/adapter/sqldb/short_link_integration_test.go
  backend/app/adapter/sqldb/table/user_changelog.go
  backend/app/adapter/sqldb/user_changelog_integration_test.go
  backend/app/adapter/sqldb/user_short_link_integration_test.go
  backend/app/adapter/sqldb/userrole.go
  backend/app/adapter/sqldb/userrole_integration_test.go
  backend/app/usecase/feature/checker.go
  backend/app/usecase/feature/decision.go
  backend/app/usecase/feature/dynamic.go
  backend/app/usecase/feature/dynamic_test.go
  backend/app/usecase/feature/static.go
  backend/dep/provider/feature.go
  backend/dep/provider/routes.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
  backend/scripts/integration-test
  frontend/src/component/App.tsx
  frontend/src/component/UIFactory.tsx
  frontend/src/dep.ts
  frontend/src/service/Auth.service.ts
  frontend/src/service/HTTP.service.ts
  frontend/src/service/ShortHTTP.api.ts
  frontend/src/service/feature-decision/DynamicDecision.service.ts
  frontend/src/service/feature-decision/FeatureDecision.service.ts
Labels: size/XL

#826 Restyle admin panel
  frontend/src/component/pages/AdminPage.scss
  frontend/src/component/styles/color.scss
  frontend/src/component/styles/layer.scss
  frontend/src/component/styles/shadow.scss
  frontend/src/component/ui/Drawer.scss
  frontend/src/component/ui/Navigation.scss
Labels: size/S

#827 Make feature toggle decision at mount time instead of build time
  frontend/src/component/UIFactory.tsx
  frontend/src/component/hoc/withFeatureToggle.tsx
  frontend/src/component/hoc/withPageAuth.tsx
  frontend/src/service/feature-decision/DynamicDecision.service.ts
Labels: bug, size/M

#829 Add basic structure for search short link
  backend/app/usecase/search/filter.go
  backend/app/usecase/search/order/order.go
  backend/app/usecase/search/query.go
  backend/app/usecase/search/search.go
Labels: size/M

#828 Add Admin button in Home Page
  frontend/src/component/App.tsx
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/HomePage.tsx
  frontend/src/component/pages/shared/Header.scss
  frontend/src/component/pages/shared/Header.tsx
Labels: enhancement, size/M

#834 Rename URL to shortlink for GraphQL queries in client side
  frontend/src/service/ShortLinkGraphQL.api.ts
  frontend/src/service/Url.service.ts
Labels: size/M

#837 Update to the latest app framework
  backend/go.mod
  backend/go.sum
Labels: size/XS

#839 Remove redundant code coverage after merged to master branch
  .drone.yml
Labels: size/XS

#836 Rename URL to shortlink for GraphQL
  backend/app/adapter/gqlapi/resolver/authmutation.go
  backend/app/adapter/gqlapi/resolver/authquery.go
  backend/app/adapter/gqlapi/resolver/authquery_test.go
  backend/app/adapter/gqlapi/resolver/url.go
  backend/app/adapter/gqlapi/resolver/url_test.go
  backend/app/adapter/gqlapi/schema.go
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
  frontend/src/service/ShortLinkGraphQL.api.ts
  frontend/src/service/Url.service.ts
Labels: size/L

#831 Update ShortLinkSql methods to include meta tags
  backend/app/adapter/sqldb/short_link.go
  backend/app/adapter/sqldb/short_link_integration_test.go
  backend/app/adapter/sqldb/table/short_link.go
  backend/app/entity/metatag/metatag.go
  backend/app/entity/shortlink.go
Labels: Go, enhancement, size/L

#841 Add ByCreatedTimeASC order for Search
  backend/app/usecase/search/order/created_time.go
  backend/app/usecase/search/order/created_time_test.go
  backend/app/usecase/search/order/order.go
  backend/app/usecase/search/order/unchanged_test.go
Labels: Go, size/L

#838 Add delete usecase and GraphQL API for ChangeLogs
  backend/app/adapter/gqlapi/resolver/authmutation.go
  backend/app/adapter/gqlapi/schema.go
  backend/app/adapter/sqldb/changelog.go
  backend/app/usecase/changelog/changelog.go
  backend/app/usecase/changelog/changelog_test.go
  backend/app/usecase/repository/change_log.go
  backend/app/usecase/repository/change_log_fake.go
Labels: enhancement, size/L

#842 Add UpdateOpenGraphMetaTags to adapter
  backend/app/adapter/sqldb/short_link.go
  backend/app/adapter/sqldb/short_link_integration_test.go
Labels: Go, enhancement, size/L

#752 Prevent '#' character from being used in custom alias
  backend/app/adapter/gqlapi/resolver/authmutation.go
  backend/app/adapter/gqlapi/resolver/error.go
  backend/app/usecase/changelog/changelog.go
  backend/app/usecase/shortlink/creator.go
  backend/app/usecase/shortlink/creator_test.go
  backend/app/usecase/validator/alias.go
  backend/app/usecase/validator/alias_test.go
  backend/app/usecase/validator/longlink.go
  backend/app/usecase/validator/longlink_test.go
  backend/app/usecase/validator/validator.go
  backend/app/usecase/validator/violation.go
  frontend/src/service/Error.service.ts
  frontend/src/validators/CustomAlias.validator.ts
Labels: size/L

#588 Add unit tests for SearchBar
  frontend/src/component/ui/SearchBar.spec.tsx
  frontend/src/component/ui/SearchBar.tsx
Labels: hold, maintainability, size/L

#796 Broken test in urlcreator_test
  backend/app/usecase/shortlink/creator_test.go
Labels: hold, size/XS

#845 Add new unauthorized error type
  backend/app/adapter/gqlapi/resolver/error.go
Labels: enhancement, size/S

#846 Add update Change logs functionality in ChangeLogs Repo
  backend/app/adapter/gqlapi/resolver/error.go
  backend/app/adapter/sqldb/changelog.go
  backend/app/adapter/sqldb/changelog_integration_test.go
  backend/app/usecase/repository/change_log.go
  backend/app/usecase/repository/change_log_fake.go
Labels: enhancement, size/L

#848 Add update Change Log Usecase and API
  backend/app/adapter/gqlapi/resolver/authmutation.go
  backend/app/adapter/gqlapi/schema.go
  backend/app/adapter/sqldb/changelog.go
  backend/app/usecase/changelog/changelog.go
  backend/app/usecase/changelog/changelog_test.go
  backend/app/usecase/repository/change_log_fake.go
Labels: enhancement, size/L

#847 Add HasMapping to sql adapter
  backend/app/adapter/sqldb/user_short_link.go
  backend/app/adapter/sqldb/user_short_link_integration_test.go
Labels: size/L

#852 Restyle changelog modal
  frontend/src/component/pages/shared/Footer.tsx
  frontend/src/component/styles/color.scss
  frontend/src/component/styles/shadow.scss
  frontend/src/component/ui/ChangeLogModal.scss
  frontend/src/component/ui/Modal.scss
  frontend/src/component/ui/ViewChangeLogButton.tsx
Labels: size/M

#853 Restyle change log title
  frontend/src/component/ui/ChangeLogModal.scss
Labels: size/XS

#855 Revert "Remove redundant code coverage after merged to master branch"
  .drone.yml
Labels: size/XS

#856 deploy
  .drone.yml
  backend/app/adapter/gqlapi/resolver/authmutation.go
  backend/app/adapter/gqlapi/resolver/error.go
  backend/app/adapter/gqlapi/schema.go
  backend/app/adapter/sqldb/changelog.go
  backend/app/adapter/sqldb/changelog_integration_test.go
  backend/app/adapter/sqldb/user_short_link.go
  backend/app/adapter/sqldb/user_short_link_integration_test.go
  backend/app/usecase/changelog/changelog.go
  backend/app/usecase/changelog/changelog_test.go
  backend/app/usecase/repository/change_log.go
  backend/app/usecase/repository/change_log_fake.go
  frontend/src/component/pages/shared/Footer.tsx
  frontend/src/component/styles/color.scss
  frontend/src/component/styles/shadow.scss
  frontend/src/component/ui/ChangeLogModal.scss
  frontend/src/component/ui/Modal.scss
  frontend/src/component/ui/ViewChangeLogButton.tsx
Labels: size/XL

#851 Remove manual string concatenation for reCaptcha API request body
  backend/app/adapter/recaptcha/recaptcha.go
  backend/app/adapter/recaptcha/recaptcha_integration_test.go
Labels: size/S

#859 Add user permission checks to change log usecases
  backend/app/adapter/gqlapi/api_test.go
  backend/app/adapter/gqlapi/resolver/authmutation.go
  backend/app/adapter/gqlapi/resolver/authquery_test.go
  backend/app/adapter/gqlapi/resolver/query_test.go
  backend/app/adapter/gqlapi/schema.go
  backend/app/adapter/recaptcha/recaptcha_integration_test.go
  backend/app/usecase/authorizer/authorizer.go
  backend/app/usecase/changelog/changelog.go
  backend/app/usecase/changelog/changelog_test.go
  backend/app/usecase/feature/dynamic_test.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: enhancement, size/L

#854 Add shortlink updater interface to use cases
  backend/app/usecase/repository/user_fake.go
  backend/app/usecase/repository/usershortlink.go
  backend/app/usecase/repository/usershortlink_fake.go
  backend/app/usecase/shortlink/updater.go
  backend/app/usecase/shortlink/updater_test.go
Labels: size/L

#861 Refactor graphQL related schemas into a singe source
  frontend/src/dep.ts
  frontend/src/service/ChangeLog.service.ts
  frontend/src/service/ShortGraphQLService/ChangeLogGraphQL.api.ts
  frontend/src/service/ShortGraphQLService/ShortLinkGraphQL.api.ts
  frontend/src/service/ShortGraphQLService/schema.ts
  frontend/src/service/ShortLink.service.ts
  frontend/src/service/Url.service.ts
Labels: refactor, size/L

#862 Rename ShortGraphQLService into shortGraphQL
  frontend/src/dep.ts
  frontend/src/service/ChangeLog.service.ts
  frontend/src/service/ShortLink.service.ts
  frontend/src/service/Url.service.ts
  frontend/src/service/shortGraphQL/ChangeLogGraphQL.api.ts
  frontend/src/service/shortGraphQL/ShortLinkGraphQL.api.ts
  frontend/src/service/shortGraphQL/schema.ts
Labels: refactor

#850 Add UpdateTwitterTags to adapter
  backend/app/adapter/sqldb/short_link.go
  backend/app/adapter/sqldb/short_link_integration_test.go
Labels: Go, enhancement, size/L

#864 Add match package
  backend/app/usecase/matcher/contains_all.go
  backend/app/usecase/matcher/contains_all_test.go
  backend/app/usecase/matcher/contains_any.go
  backend/app/usecase/matcher/contains_any_test.go
Labels: Go, enhancement, size/L

#849 Search Short Link resource
  backend/app/usecase/search/search.go
  backend/app/usecase/search/search_test.go
Labels: Go, size/XL

#867 Add api/search route
  backend/.env.dist
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
  backend/app/app.go
  backend/app/usecase/search/search.go
  backend/app/usecase/search/search_test.go
  backend/dep/provider/routes.go
  backend/dep/provider/search.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/main.go
Labels: Go, enhancement, size/M

#868 Remove renaming of net/url package
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
Labels: Go, refactor, size/S

#870 Add constructor for Filter
  backend/app/usecase/search/filter.go
  backend/app/usecase/search/filter_test.go
  backend/app/usecase/search/search.go
  backend/app/usecase/search/search_test.go
Labels: bug, size/L

#874 Remove unused observability package
  backend/app/usecase/observability/obervability.go
Labels: maintainability, size/S

#875 Remove unnecessary dereference operator
  backend/app/adapter/sqldb/short_link.go
  backend/app/adapter/sqldb/short_link_integration_test.go
  backend/app/adapter/sqldb/user.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: maintainability, size/M

#873 Refactor routing package
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/handle/analytics.go
  backend/app/adapter/routing/handle/feature.go
  backend/app/adapter/routing/handle/handle.go
  backend/app/adapter/routing/handle/long_link.go
  backend/app/adapter/routing/handle/search.go
  backend/app/adapter/routing/handle/sso_signin.go
  backend/app/adapter/routing/handle/token.go
  backend/app/adapter/routing/route.go
  backend/app/adapter/routing/token.go
Labels: Go, refactor, size/L

#876 Add update short link api
  backend/app/adapter/gqlapi/api_test.go
  backend/app/adapter/gqlapi/resolver/authmutation.go
  backend/app/adapter/gqlapi/resolver/mutation.go
  backend/app/adapter/gqlapi/resolver/resolver.go
  backend/app/adapter/gqlapi/schema.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: size/L

#871 Add MetaTagPersist to usecase
  backend/app/usecase/shortlink/metatag.go
  backend/app/usecase/shortlink/metatag_test.go
Labels: Go, enhancement, size/L

#882 Response to the Search API request
  backend/app/adapter/routing/handle/search.go
  backend/app/usecase/search/search.go
  backend/app/usecase/search/search_test.go
Labels: Go, enhancement, size/L

#884 Fix bug for concurrent search of resources
  backend/app/usecase/search/search.go
  backend/app/usecase/search/search_test.go
Labels: Go, bug, size/M

#886 Integrate update short link API with frontend
  frontend/src/dep.ts
  frontend/src/service/Captcha.service.ts
  frontend/src/service/ShortLink.service.ts
  frontend/src/service/shortGraphQL/ShortLinkGraphQL.api.ts
  frontend/src/service/shortGraphQL/schema.ts
Labels: size/M

#887 Keep local state for TextField and add default text
  frontend/src/component/form/TextField.scss
  frontend/src/component/form/TextField.tsx
  frontend/src/component/pages/shared/CreateShortLinkSection.tsx
Labels: size/M

#888 Add edit and check icons
  frontend/src/component/ui/Icon.tsx
Labels: size/M

#885 Add instrumentation for Search API
  backend/app/adapter/routing/handle/search.go
  backend/app/adapter/routing/route.go
  backend/app/usecase/instrumentation/instrumentation.go
Labels: Go, enhancement, size/M

#892 Update GITHUB.md
  doc/sso/GITHUB.md
Labels: documentation, size/S

#896 Update app framework to serve GraphQL api doc
  backend/.env.dist
  backend/app/app.go
  backend/dep/provider/graphql.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
  backend/main.go
Labels: documentation, size/M

#895 Extract error modal into a separate component
  frontend/src/component/pages/HomePage.scss
  frontend/src/component/pages/HomePage.tsx
  frontend/src/component/pages/shared/ErrorModal.scss
  frontend/src/component/pages/shared/ErrorModal.tsx
  frontend/src/component/styles/color.scss
Labels: refactor, size/L

#899 Fix invalid color reference in error modal
  frontend/src/component/pages/shared/ErrorModal.scss
Labels: bug, size/XS

#897 deploy
  backend/.env.dist
  backend/app/app.go
  backend/dep/provider/graphql.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
  backend/main.go
  frontend/src/component/pages/HomePage.scss
  frontend/src/component/pages/HomePage.tsx
  frontend/src/component/pages/shared/ErrorModal.scss
  frontend/src/component/pages/shared/ErrorModal.tsx
  frontend/src/component/styles/color.scss
Labels: size/L

#901 Add documentation for GraphQL apis
  backend/app/adapter/gqlapi/schema.go
  frontend/src/component/ui/Icon.tsx
  frontend/src/service/shortGraphQL/ShortLinkGraphQL.api.ts
  frontend/src/service/shortGraphQL/schema.ts
Labels: size/L

#902 Center align changelog 'view all updates' button
  frontend/src/component/ui/ChangeLogModal.scss
Labels: size/XS

#900 Add create change service APIs
  frontend/src/service/Captcha.service.ts
  frontend/src/service/ChangeLog.service.ts
  frontend/src/service/Error.service.ts
  frontend/src/service/GraphQLError.ts
  frontend/src/service/shortGraphQL/ChangeLogGraphQL.api.ts
  frontend/src/service/shortGraphQL/schema.ts
Labels: enhancement, size/M

#906 Add delete client services
  frontend/src/service/Captcha.service.ts
  frontend/src/service/ChangeLog.service.ts
  frontend/src/service/shortGraphQL/ChangeLogGraphQL.api.ts
  frontend/src/service/shortGraphQL/schema.ts
Labels: enhancement, size/M

#908 Add prototype for feedback widget
  widget/emotic/.prettierrc
  widget/emotic/example/package.json
  widget/emotic/example/src/App.scss
  widget/emotic/example/src/App.test.tsx
  widget/emotic/example/src/App.tsx
  widget/emotic/example/src/index.tsx
  widget/emotic/example/src/setupTests.ts
  widget/emotic/example/tsconfig.json
  widget/emotic/example/yarn.lock
  widget/emotic/package.json
  widget/emotic/src/component/Button.scss
  widget/emotic/src/component/Button.tsx
  widget/emotic/src/component/Emotic.tsx
  widget/emotic/src/component/FeedbackModal.scss
  widget/emotic/src/component/FeedbackModal.tsx
  widget/emotic/src/component/Launcher.scss
  widget/emotic/src/component/Launcher.tsx
  widget/emotic/src/component/Promotion.scss
  widget/emotic/src/component/Promotion.tsx
  widget/emotic/src/component/close.svg
  widget/emotic/src/component/face.svg
  widget/emotic/src/component/tabs/CollectEmailTab.scss
  widget/emotic/src/component/tabs/CollectEmailTab.tsx
  widget/emotic/src/component/tabs/EmotionTab.scss
  widget/emotic/src/component/tabs/EmotionTab.tsx
  widget/emotic/src/component/tabs/ThankYouTab.scss
  widget/emotic/src/component/tabs/ThankYouTab.tsx
  widget/emotic/src/component/tabs/emotion/frustrated.svg
  widget/emotic/src/component/tabs/emotion/happy.svg
  widget/emotic/src/component/tabs/emotion/love.svg
  widget/emotic/src/component/tabs/emotion/neutral.svg
  widget/emotic/src/component/tabs/emotion/sad.svg
  widget/emotic/src/entity/emotion.ts
  widget/emotic/src/entity/feedback.ts
  widget/emotic/src/index.test.tsx
  widget/emotic/src/index.tsx
  widget/emotic/src/styles.module.scss
  widget/emotic/src/typings.d.ts
  widget/emotic/yarn.lock
Labels: size/XXL

#905 Add Change getter graphQL api
  backend/app/adapter/gqlapi/resolver/authquery.go
  backend/app/adapter/gqlapi/schema.go
  backend/app/usecase/authorizer/authorizer.go
  backend/app/usecase/changelog/changelog.go
  backend/app/usecase/changelog/changelog_test.go
Labels: enhancement, size/L

#909 Add get all changes client services
  frontend/src/service/ChangeLog.service.ts
  frontend/src/service/shortGraphQL/ChangeLogGraphQL.api.ts
  frontend/src/service/shortGraphQL/schema.ts
Labels: enhancement, size/M

#910 Append Emotic to all component styles to avoid style leaking
  widget/emotic/src/component/Button.scss
  widget/emotic/src/component/Button.tsx
  widget/emotic/src/component/FeedbackModal.scss
  widget/emotic/src/component/FeedbackModal.tsx
  widget/emotic/src/component/Launcher.scss
  widget/emotic/src/component/Launcher.tsx
  widget/emotic/src/component/Promotion.scss
  widget/emotic/src/component/Promotion.tsx
  widget/emotic/src/component/tabs/CollectEmailTab.scss
  widget/emotic/src/component/tabs/CollectEmailTab.tsx
  widget/emotic/src/component/tabs/EmotionTab.scss
  widget/emotic/src/component/tabs/EmotionTab.tsx
  widget/emotic/src/component/tabs/ThankYouTab.scss
  widget/emotic/src/component/tabs/ThankYouTab.tsx
Labels: size/S

#911 deploy
  backend/app/adapter/gqlapi/resolver/authquery.go
  backend/app/adapter/gqlapi/schema.go
  backend/app/usecase/authorizer/authorizer.go
  backend/app/usecase/changelog/changelog.go
  backend/app/usecase/changelog/changelog_test.go
  frontend/src/service/Captcha.service.ts
  frontend/src/service/ChangeLog.service.ts
  frontend/src/service/shortGraphQL/ChangeLogGraphQL.api.ts
  frontend/src/service/shortGraphQL/schema.ts
  widget/emotic/.prettierrc
  widget/emotic/example/package.json
  widget/emotic/example/src/App.scss
  widget/emotic/example/src/App.test.tsx
  widget/emotic/example/src/App.tsx
  widget/emotic/example/src/index.tsx
  widget/emotic/example/src/setupTests.ts
  widget/emotic/example/tsconfig.json
  widget/emotic/example/yarn.lock
  widget/emotic/package.json
  widget/emotic/src/component/Button.scss
  widget/emotic/src/component/Button.tsx
  widget/emotic/src/component/Emotic.tsx
  widget/emotic/src/component/FeedbackModal.scss
  widget/emotic/src/component/FeedbackModal.tsx
  widget/emotic/src/component/Launcher.scss
  widget/emotic/src/component/Launcher.tsx
  widget/emotic/src/component/Promotion.scss
  widget/emotic/src/component/Promotion.tsx
  widget/emotic/src/component/close.svg
  widget/emotic/src/component/face.svg
  widget/emotic/src/component/tabs/CollectEmailTab.scss
  widget/emotic/src/component/tabs/CollectEmailTab.tsx
  widget/emotic/src/component/tabs/EmotionTab.scss
  widget/emotic/src/component/tabs/EmotionTab.tsx
  widget/emotic/src/component/tabs/ThankYouTab.scss
  widget/emotic/src/component/tabs/ThankYouTab.tsx
  widget/emotic/src/component/tabs/emotion/frustrated.svg
  widget/emotic/src/component/tabs/emotion/happy.svg
  widget/emotic/src/component/tabs/emotion/love.svg
  widget/emotic/src/component/tabs/emotion/neutral.svg
  widget/emotic/src/component/tabs/emotion/sad.svg
  widget/emotic/src/entity/emotion.ts
  widget/emotic/src/entity/feedback.ts
  widget/emotic/src/index.test.tsx
  widget/emotic/src/index.tsx
  widget/emotic/src/styles.module.scss
  widget/emotic/src/typings.d.ts
  widget/emotic/yarn.lock
Labels: size/XXL

#912 Update Emotic README
  widget/emotic/README.md
Labels: size/XS

#913 Add update change client service methods
  frontend/src/service/Captcha.service.ts
  frontend/src/service/ChangeLog.service.ts
  frontend/src/service/shortGraphQL/ChangeLogGraphQL.api.ts
  frontend/src/service/shortGraphQL/schema.ts
Labels: enhancement, size/M

#914 Separate GraphQL schema into .graphql file
  backend/.env.dist
  backend/Dockerfile
  backend/app/adapter/gqlapi/api.go
  backend/app/adapter/gqlapi/api_test.go
  backend/app/adapter/gqlapi/schema.go
  backend/app/adapter/gqlapi/schema.graphql
  backend/app/app.go
  backend/app/fw/filesystem/filesystem.go
  backend/app/fw/filesystem/local.go
  backend/dep/provider/graphql.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.sum
  backend/main.go
Labels: maintainability, size/L
