Repository short-d/short, pull requests merged in 2020-08, with the labels that each got.

#989 Rename originalLink into longLink in client side components
  frontend/src/component/pages/shared/CreateShortLinkSection.tsx
  frontend/src/component/pages/shared/ShortLinkUsage.tsx
  frontend/src/component/pages/shared/UserShortLinksSection.spec.tsx
  frontend/src/component/pages/shared/UserShortLinksSection.tsx
  frontend/src/component/ui/SearchBar.spec.tsx
  frontend/src/component/ui/SearchBar.tsx
  frontend/src/entity/ShortLink.tsx
  frontend/src/service/Search.service.ts
  frontend/src/service/ShortLink.service.ts
  frontend/src/service/shortGraphQL/ShortLinkGraphQL.api.ts
  frontend/src/state/reducers.ts
Labels: React, refactor, size/L

#990 Move feedback widget out of Short's repo
  widget/emotic/.editorconfig
  widget/emotic/.eslintignore
  widget/emotic/.eslintrc
  widget/emotic/.gitignore
  widget/emotic/.prettierrc
  widget/emotic/README.md
  widget/emotic/example/README.md
  widget/emotic/example/package.json
  widget/emotic/example/public/favicon.ico
  widget/emotic/example/public/index.html
  widget/emotic/example/public/manifest.json
  widget/emotic/example/src/App.scss
  widget/emotic/example/src/App.tsx
  widget/emotic/example/src/index.scss
  widget/emotic/example/src/index.tsx
  widget/emotic/example/src/react-app-env.d.ts
  widget/emotic/example/src/setupTests.ts
  widget/emotic/example/tsconfig.json
  widget/emotic/example/yarn.lock
  widget/emotic/package.json
  widget/emotic/src/.eslintrc
  widget/emotic/src/component/Button.scss
  widget/emotic/src/component/Button.tsx
  widget/emotic/src/component/Emotic.tsx
  widget/emotic/src/component/FeedbackModal.scss
  widget/emotic/src/component/FeedbackModal.tsx
  widget/emotic/src/component/Launcher.scss
  widget/emotic/src/component/Launcher.tsx
  widget/emotic/src/component/Promotion.scss
  widget/emotic/src/component/Promotion.tsx
  widget/emotic/src/component/close.svg
  widget/emotic/src/component/face.svg
  widget/emotic/src/component/tabs/CollectEmailTab.scss
  widget/emotic/src/component/tabs/CollectEmailTab.tsx
  widget/emotic/src/component/tabs/EmotionTab.scss
  widget/emotic/src/component/tabs/EmotionTab.tsx
  widget/emotic/src/component/tabs/ThankYouTab.scss
  widget/emotic/src/component/tabs/ThankYouTab.tsx
  widget/emotic/src/component/tabs/emotion/frustrated.svg
  widget/emotic/src/component/tabs/emotion/happy.svg
  widget/emotic/src/component/tabs/emotion/love.svg
  widget/emotic/src/component/tabs/emotion/neutral.svg
  widget/emotic/src/component/tabs/emotion/sad.svg
  widget/emotic/src/entity/emotion.ts
  widget/emotic/src/entity/feedback.ts
  widget/emotic/src/index.tsx
  widget/emotic/src/typings.d.ts
  widget/emotic/tsconfig.json
  widget/emotic/tsconfig.test.json
  widget/emotic/yarn.lock
Labels: maintainability

#991 Add green Button to storybook
  story/src/0-Button.stories.tsx
Labels: size/XS

#988 Add styles to Toggle
  frontend/src/component/styles/shadow.scss
  frontend/src/component/ui/Toggle.module.scss
  frontend/src/component/ui/Toggle.tsx
  story/src/1-Toggle.stories.tsx
Labels: size/M

#992 Use ptr.String for test cases that contain strings
  backend/app/adapter/gqlapi/resolver/query_test.go
  backend/app/adapter/sqldb/changelog_integration_test.go
  backend/app/usecase/changelog/changelog_test.go
  backend/app/usecase/shortlink/metatag_test.go
Labels: size/L

#975 Serve custom meta tags for the UI when users visits /r/:alias
  frontend/.gitignore
  frontend/package.json
  frontend/public/index.html
  frontend/serve/entity/open_graph_tag.go
  frontend/serve/entity/twitter_tag.go
  frontend/serve/go.mod
  frontend/serve/go.sum
  frontend/serve/handle/file.go
  frontend/serve/handle/redirect.go
  frontend/serve/main.go
  frontend/serve/scripts/dev
  frontend/serve/scripts/format
  frontend/serve/shortapi/grpc.go
  frontend/serve/ssr/page.go
  frontend/serve/ssr/page_test.go
  frontend/serve/ssr/redirect.go
Labels: Go, enhancement, size/L

#969 Add deletion feature to short link repository
  backend/app/adapter/sqldb/short_link.go
  backend/app/adapter/sqldb/short_link_integration_test.go
  backend/app/usecase/repository/shortlink.go
  backend/app/usecase/repository/shortlink_fake.go
Labels: size/L

#994 Add localhost for swagger docs
  backend/app/adapter/routing/api.yml
Labels: size/XS

#997 Merge into prod: localhost api docs and delete-short-link feature
  backend/app/adapter/routing/api.yml
  backend/app/adapter/sqldb/short_link.go
  backend/app/adapter/sqldb/short_link_integration_test.go
  backend/app/usecase/repository/shortlink.go
  backend/app/usecase/repository/shortlink_fake.go
Labels: size/L

#1004 Update frontend dockerfile to support SSR
  frontend/Dockerfile
  frontend/serve/handle/redirect.go
  frontend/serve/main.go
Labels: Go, enhancement, size/M

#1002 Add Icon story
  story/src/2-Icon.stories.module.scss
  story/src/2-Icon.stories.tsx
Labels: size/M

#1009 Remove addon-info from Icon story
  story/src/2-Icon.stories.tsx
Labels: size/M

#1008 Add Notice story
  frontend/src/component/ui/Notice.module.scss
  frontend/src/component/ui/Notice.tsx
  story/src/3-Notice.stories.module.scss
  story/src/3-Notice.stories.tsx
Labels: size/S
