Repository short-d/short, pull requests merged in 2020-01, with the labels that each got.

#468 Update build status in README
  README.md
Labels: documentation

#470 Move migration into db directory
  backend/Dockerfile
  backend/app/adapter/db/.env
  backend/app/adapter/db/migration/1_create_url_table.sql
  backend/app/adapter/db/migration/2_create_user_table.sql
  backend/app/adapter/db/migration/3_rename_url_table_and_columns.sql
  backend/app/adapter/db/migration/4_rename_user_table_and_columns.sql
  backend/app/adapter/db/migration/5_create_user_url_relation_table.sql
  backend/app/adapter/db/migration/6_add_user_id_column.sql
  backend/app/adapter/db/migration/7_create_github_oauth_user_relation_table.sql
  backend/app/adapter/db/migration/8_create_public_url_table.sql
  backend/app/adapter/db/migration/9_change_url_alias_type.sql
  backend/cmd/cmd.go
Labels: maintainability

#471 Update badges on README
  README.md
Labels: documentation

#472 Add empty line
  backend/main.go
Labels: maintainability

#474 Fix comments
  backend/dep/provider/logger.go
Labels: maintainability

#476 Implement CreateMapping for GithubSSOSql repository
  backend/app/adapter/db/githubsso.go
  backend/app/adapter/db/githubsso_integration_test.go
  backend/app/adapter/db/migration/11_add_uniqueness_to_githubsso_table.sql
Labels: enhancement

#478 Support retrieving Github user ID
  backend/app/adapter/github/account.go
  backend/app/adapter/github/account_integration_test.go
  backend/app/adapter/recaptcha/recaptcha_integration_test.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
Labels: enhancement

#481 Fix build flag for Github account integration test
  backend/app/adapter/github/account_integration_test.go
Labels: bug

#479 Add gateway integration test for Google account API
  backend/app/adapter/google/account_integration_test.go
Labels: maintainability

#485 Add query parameter to autofill long link
  frontend/src/component/form/TextField.tsx
  frontend/src/component/pages/Home.tsx
Labels: enhancement

#484 Add Google OAuth configuration to README and .env.dist
  README.md
  backend/.env.dist
  doc/google/OAuth.jpg
  doc/google/credentials.jpg
Labels: documentation

#490 Fix Google sign in screenshot not correctly displayed in the README
  README.md
Labels: documentation

#489 Fix Google sign in section missing from the table of contents
  README.md
Labels: documentation

#486 Add Presenter interface
  backend/app/usecase/presenter.go
Labels: enhancement

#496 Add Alexander as code owner for Go language
  .github/CODEOWNERS
Labels: maintainability

#498 Add integration test for google OAuth IdentityProvider
  backend/app/adapter/google/identityprovider_integration_test.go
Labels: maintainability

#499 Add integration test for Github OAuth IdentityProvider
  backend/app/adapter/github/identityprovider_integration_test.go
Labels: enhancement

#500 Refactor account for Facebook OAuth
  backend/app/adapter/facebook/account.go
  backend/app/adapter/facebook/account_integration_test.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
Labels: enhancement

#501 Refactor IdentityProvider for Facebook OAuth
  backend/app/adapter/facebook/identityprovider.go
  backend/app/adapter/facebook/identityprovider_integration_test.go
Labels: enhancement

#504 Fix empty email bug
  backend/app/usecase/auth/authenticator.go
  backend/app/usecase/auth/authenticator_test.go
Labels: bug
