Repository short-d/short, pull requests merged in 2020-05, with the labels that each got.

#726 Add navigation component
  frontend/src/component/ui/Navigation.scss
  frontend/src/component/ui/Navigation.spec.tsx
  frontend/src/component/ui/Navigation.tsx
Labels: enhancement, size/L

#727 Add drawer component
  frontend/src/component/ui/Drawer.scss
  frontend/src/component/ui/Drawer.spec.tsx
  frontend/src/component/ui/Drawer.tsx
Labels: enhancement, size/L

#507 Add to public url toggle create short link section
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/Home.tsx
  frontend/src/component/pages/shared/CreateShortLinkSection.scss
  frontend/src/component/pages/shared/CreateShortLinkSection.tsx
  frontend/src/component/pages/shared/PublicListingToggle.scss
  frontend/src/component/pages/shared/PublicListingToggle.spec.tsx
  frontend/src/component/pages/shared/PublicListingToggle.tsx
  frontend/src/component/ui/Navigation.spec.tsx
  frontend/src/component/ui/Toggle.scss
  frontend/src/component/ui/Toggle.tsx
  frontend/src/service/Url.service.ts
  frontend/src/service/feature-decision/DynamicDecision.service.ts
  frontend/src/service/feature-decision/FeatureDecision.service.ts
Labels: enhancement, size/L

#731 Replace material icons with custom Icon component
  frontend/src/component/pages/HomePage.scss
  frontend/src/component/pages/HomePage.tsx
  frontend/src/component/styles/icon.scss
  frontend/src/component/ui/ChangeLogModal.scss
  frontend/src/component/ui/ChangeLogModal.tsx
  frontend/src/component/ui/Icon.scss
  frontend/src/component/ui/Icon.spec.tsx
  frontend/src/component/ui/Icon.tsx
  frontend/src/component/ui/SearchBar.scss
  frontend/src/component/ui/SearchBar.tsx
Labels: enhancement, size/L

#737 Upgrade prettier to 1.19.1
  frontend/package.json
  frontend/yarn.lock
Labels: size/S

#735 Toggle unit test
  frontend/src/component/ui/Toggle.spec.tsx
Labels: size/M

#741 Generate random alias if empty alias provided
  backend/app/usecase/url/urlcreator.go
  backend/app/usecase/url/urlcreator_test.go
  frontend/src/service/Url.service.ts
Labels: size/M

#734 Implement GetLastViewedAt
  backend/app/adapter/gqlapi/api_test.go
  backend/app/adapter/gqlapi/resolver/authquery.go
  backend/app/adapter/gqlapi/resolver/authquery_test.go
  backend/app/adapter/gqlapi/resolver/query_test.go
  backend/app/usecase/changelog/changelog.go
  backend/app/usecase/changelog/changelog_test.go
  backend/app/usecase/repository/user_changelog_fake.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: Go, enhancement, size/L

#749 Add tabs component
  frontend/src/component/ui/Tabs.spec.tsx
  frontend/src/component/ui/Tabs.tsx
Labels: enhancement, size/L

#750 Admin panel
  frontend/src/component/pages/AdminPage.scss
  frontend/src/component/pages/AdminPage.tsx
  frontend/src/component/styles/shadow.scss
Labels: enhancement, size/L

#751 Refactor Navigation Menu Items spacing
  frontend/src/component/ui/Navigation.scss
Labels: enhancement, size/XS

#754 Implement ViewChangeLog
  backend/app/usecase/changelog/changelog.go
  backend/app/usecase/changelog/changelog_test.go
Labels: Go, enhancement, size/M

#756 Implement viewChangeLog GraphQL API
  backend/app/adapter/gqlapi/resolver/authmutation.go
  backend/app/adapter/gqlapi/schema.go
Labels: Go, enhancement, size/S

#757 Add Authorizer to manager user roles and permission
  backend/app/adapter/sqldb/migration/15_create_user_role_table.sql
  backend/app/adapter/sqldb/table/userrole.go
  backend/app/adapter/sqldb/userrole.go
  backend/app/adapter/sqldb/userrole_integration_test.go
  backend/app/entity/empty.go
  backend/app/usecase/authorizer/authorizer.go
  backend/app/usecase/authorizer/authorizer_test.go
  backend/app/usecase/authorizer/rbac/permission/permission.go
  backend/app/usecase/authorizer/rbac/rbac.go
  backend/app/usecase/authorizer/rbac/rbac_test.go
  backend/app/usecase/authorizer/rbac/role/role.go
  backend/app/usecase/repository/error.go
  backend/app/usecase/repository/user_changelog.go
  backend/app/usecase/repository/userrole.go
  backend/app/usecase/repository/userrole_fake.go
Labels: size/XL

#758 Update system diagrams in the README
  README.md
  doc/clean-architecture/clean-architecture.jpg
  doc/clean-architecture/short-backend.jpg
  doc/cloud/overall.jpg
  doc/db/er.jpg
  doc/deployment/cd-pipeline.jpg
  doc/deployment/gitops.jpg
  doc/devops/continuous-delivery.png
  doc/devops/continuous-deployment.png
  doc/eng/clean-architecture/boundary.jpg
  doc/eng/clean-architecture/finance-app.jpg
  doc/eng/db/er-v1.jpg
  doc/eng/db/er-v1.txt
  doc/eng/db/er-v2.txt
  doc/eng/microservices.jpg
  doc/tutorial/CI-CD.md
  doc/tutorial/POSTGRES.md
Labels: documentation

#761 Remove clean architecture diagram
  README.md
  doc/clean-architecture/clean-architecture.jpg
Labels: documentation

#762 Remove images from Getting Started section
  README.md
Labels: size/S

#763 Move Facebook & Github oauth config into separate files
  README.md
  doc/sso/FACEBOOK.md
  doc/sso/GITHUB.md
Labels: size/M

#764 Remove unused images in repo resources
  doc/facebook/credentials.jpg
  doc/facebook/login.jpg
  doc/github/credentials.jpg
  doc/github/new-oauth-app.jpg
  doc/github/oauth-apps.jpg
  doc/google/OAuth.jpg
  doc/google/credentials.jpg
  doc/recaptcha/credentials.jpg
  doc/recaptcha/register-site.jpg
  doc/recaptcha/settings.jpg
Labels: maintainability

#765 Switch primary key from email to user ID
  backend/app/adapter/sqldb/migration/16_switch_from_email_to_id.sql
  backend/app/adapter/sqldb/migration/17_add_constraints_to_user_role_table.sql
  backend/app/adapter/sqldb/migration/18_alter_githubsso_table.sql
  backend/app/adapter/sqldb/migration/19_add_constraints_to_user_changelog_table.sql
  backend/app/adapter/sqldb/table/userurl.go
  backend/app/adapter/sqldb/userurl.go
  backend/app/adapter/sqldb/userurl_integration_test.go
Labels: size/L

#767 Add Google & Facebook SSO DB table
  backend/app/adapter/sqldb/migration/20_create_facebook_sso_table.sql
  backend/app/adapter/sqldb/migration/21_create_google_sso_table.sql
  backend/app/adapter/sqldb/migration/22_add_cascade_to_githubsso_table.sql
Labels: size/M

#768 Clean up Google & Facebook identify providers
  backend/app/adapter/facebook/identityprovider.go
  backend/app/adapter/facebook/identityprovider_integration_test.go
  backend/app/adapter/github/identityprovider.go
  backend/app/adapter/google/identityprovider.go
  backend/app/adapter/google/identityprovider_integration_test.go
Labels: maintainability, size/M

#769 Fix Github account API
  backend/app/adapter/github/account.go
Labels: size/XS

#773 Parallelize automated tests
  backend/app/adapter/facebook/account_integration_test.go
  backend/app/adapter/facebook/identityprovider_integration_test.go
  backend/app/adapter/github/account_integration_test.go
  backend/app/adapter/github/identityprovider_integration_test.go
  backend/app/adapter/google/account_integration_test.go
  backend/app/adapter/google/identityprovider_integration_test.go
  backend/app/adapter/gqlapi/api_test.go
  backend/app/adapter/gqlapi/resolver/authquery_test.go
  backend/app/adapter/gqlapi/resolver/query_test.go
  backend/app/adapter/gqlapi/resolver/url_test.go
  backend/app/adapter/recaptcha/recaptcha_integration_test.go
  backend/app/usecase/account/provider_test.go
  backend/app/usecase/authenticator/authenticator_test.go
  backend/app/usecase/authorizer/authorizer_test.go
  backend/app/usecase/feature/dynamic_test.go
Labels: size/M

#771 Rename ShortGraphQLApi to ShortLinkGraphQLApi
  frontend/src/dep.ts
  frontend/src/service/GraphQLError.ts
  frontend/src/service/ShortLink.service.ts
  frontend/src/service/ShortLinkGraphQL.api.ts
Labels: React, maintainability, size/M

#774 Remove external package
  backend/app/adapter/facebook/account.go
  backend/app/adapter/facebook/identityprovider.go
  backend/app/adapter/github/account.go
  backend/app/adapter/github/identityprovider.go
  backend/app/adapter/google/account.go
  backend/app/adapter/google/identityprovider.go
  backend/app/adapter/gqlapi/api_test.go
  backend/app/adapter/gqlapi/resolver/authquery_test.go
  backend/app/adapter/gqlapi/resolver/query_test.go
  backend/app/adapter/kgs/kgs.go
  backend/app/adapter/recaptcha/recaptcha.go
  backend/app/adapter/recaptcha/recaptcha_integration_test.go
  backend/app/adapter/routing/handle.go
  backend/app/usecase/account/linker_test.go
  backend/app/usecase/account/ssoaccount.go
  backend/app/usecase/account/ssoaccount_fake.go
  backend/app/usecase/changelog/changelog_test.go
  backend/app/usecase/external/oauth.go
  backend/app/usecase/external/oauth_fake.go
  backend/app/usecase/keygen/keyfetcher.go
  backend/app/usecase/keygen/keyfetcher_fake.go
  backend/app/usecase/keygen/keygen.go
  backend/app/usecase/keygen/keygen_test.go
  backend/app/usecase/requester/recaptcha.go
  backend/app/usecase/requester/recaptcha_fake.go
  backend/app/usecase/requester/verifier.go
  backend/app/usecase/sso/identityprovider.go
  backend/app/usecase/sso/identityprovider_fake.go
  backend/app/usecase/sso/sso.go
  backend/app/usecase/sso/sso_test.go
  backend/app/usecase/url/urlcreator_test.go
  backend/dep/provider/keygen.go
  backend/dep/provider/recaptcha.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
Labels: maintainability, size/L

#776 Move sso account and account linker into sso package
  backend/app/adapter/facebook/account.go
  backend/app/adapter/github/account.go
  backend/app/adapter/google/account.go
  backend/app/usecase/account/ssoaccount_fake.go
  backend/app/usecase/sso/account.go
  backend/app/usecase/sso/account_fake.go
  backend/app/usecase/sso/linker.go
  backend/app/usecase/sso/linker_test.go
  backend/app/usecase/sso/sso.go
  backend/app/usecase/sso/sso_test.go
Labels: maintainability, size/M

#777 Use user ID to uniquely identify an user
  backend/app/adapter/facebook/sso.go
  backend/app/adapter/github/account.go
  backend/app/adapter/github/sso.go
  backend/app/adapter/google/sso.go
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
  backend/app/adapter/sqldb/user.go
  backend/app/adapter/sqldb/user_integration_test.go
  backend/app/usecase/account/provider.go
  backend/app/usecase/account/provider_test.go
  backend/app/usecase/authenticator/authenticator.go
  backend/app/usecase/authenticator/authenticator_test.go
  backend/app/usecase/authenticator/payload.go
  backend/app/usecase/authenticator/payload/email.go
  backend/app/usecase/authenticator/payload/email_test.go
  backend/app/usecase/authenticator/payload/factory.go
  backend/app/usecase/authenticator/payload/factory_stub.go
  backend/app/usecase/authenticator/payload/payload.go
  backend/app/usecase/authenticator/payload/payload_stub.go
  backend/app/usecase/repository/ssomap_fake.go
  backend/app/usecase/repository/user.go
  backend/app/usecase/repository/user_fake.go
  backend/app/usecase/sso/linker.go
  backend/app/usecase/sso/linker_test.go
  backend/app/usecase/sso/sso.go
  backend/app/usecase/sso/sso_test.go
  backend/dep/provider/facebook.go
  backend/dep/provider/github.go
  backend/dep/provider/google.go
  backend/dep/provider/routes.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
Labels: size/XXL

#778 Ignore frontend dev env
  .gitignore
  README.md
  backend/.gitignore
  frontend/.env.development.dist
  frontend/.gitignore
Labels: maintainability

#779 Auto generate ID for existing accounts during account linking
  backend/app/adapter/sqldb/user.go
  backend/app/adapter/sqldb/user_integration_test.go
  backend/app/usecase/repository/user.go
  backend/app/usecase/repository/user_fake.go
  backend/app/usecase/sso/linker.go
  backend/app/usecase/sso/linker_test.go
Labels: size/L

#780 Extract preference toggles into a separate subsection
  backend/app/usecase/feature/static.go
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/shared/CreateShortLinkSection.scss
  frontend/src/component/pages/shared/CreateShortLinkSection.tsx
  frontend/src/component/pages/shared/PreferenceTogglesSubSection.scss
  frontend/src/component/pages/shared/PreferenceTogglesSubSection.tsx
  frontend/src/service/feature-decision/DynamicDecision.service.ts
  frontend/src/service/feature-decision/FeatureDecision.service.ts
Labels: size/M

#782 Revert "Auto generate ID for existing accounts during account linking"
  backend/app/adapter/sqldb/user.go
  backend/app/adapter/sqldb/user_integration_test.go
  backend/app/usecase/repository/user.go
  backend/app/usecase/repository/user_fake.go
  backend/app/usecase/sso/linker.go
  backend/app/usecase/sso/linker_test.go
Labels: size/L

#783 deploy
  backend/app/adapter/sqldb/user.go
  backend/app/adapter/sqldb/user_integration_test.go
  backend/app/usecase/repository/user.go
  backend/app/usecase/repository/user_fake.go
  backend/app/usecase/sso/linker.go
  backend/app/usecase/sso/linker_test.go
Labels: size/L

#784 Use user_id instead of email in UserChangeLog adapter
  backend/app/adapter/sqldb/user_changelog.go
Labels: Go, size/S

#766 Implement ChangeLogGraphQLApi
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/HomePage.tsx
  frontend/src/component/ui/ChangeLogModal.spec.tsx
  frontend/src/component/ui/ChangeLogModal.tsx
  frontend/src/dep.ts
  frontend/src/entity/Change.tsx
  frontend/src/entity/ChangeLog.tsx
  frontend/src/entity/Update.tsx
  frontend/src/service/ChangeLog.service.ts
  frontend/src/service/ChangeLogGraphQL.api.ts
  frontend/src/state/actions.ts
  frontend/src/state/reducers.ts
Labels: React, enhancement, size/L

#786 Use UTC time when creating new Change
  backend/app/usecase/changelog/changelog.go
  backend/app/usecase/changelog/changelog_test.go
Labels: Go, enhancement, size/XS

#787 Add migration to set title and released_at to not null
  backend/app/adapter/sqldb/migration/23_set_title_and_released_at_to_not_null_changelog.sql
Labels: enhancement, size/XS

#785 Integrate change log api with the frontend
  frontend/src/component/pages/HomePage.tsx
  frontend/src/component/ui/ChangeLogModal.tsx
  frontend/src/component/ui/Modal.tsx
  frontend/src/dep.ts
  frontend/src/service/Captcha.service.ts
  frontend/src/service/ChangeLog.service.ts
  frontend/src/service/ChangeLogGraphQL.api.ts
Labels: React, enhancement, size/M

#788 Add ID migration tool
  backend/cmd/cmd.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
  backend/tool/data.go
Labels: size/L

#791 Environment variables for API ports
  backend/.env.dist
Labels: documentation, size/XS

#792 Upgrade to the latest app framework
  backend/app/adapter/gqlapi/api.go
  backend/app/adapter/gqlapi/api_test.go
  backend/app/adapter/gqlapi/resolver/resolver.go
  backend/app/adapter/kgs/kgs.go
  backend/dep/provider/entryrepo.go
  backend/dep/provider/logger.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  backend/go.mod
  backend/go.sum
Labels: size/M

#795 Rename database tables and columns
  backend/app/adapter/sqldb/migration/24_rename_url_to_short_link.sql
  backend/app/adapter/sqldb/short_link.go
  backend/app/adapter/sqldb/short_link_integration_test.go
  backend/app/adapter/sqldb/table/short_link.go
  backend/app/adapter/sqldb/table/user_short_link.go
  backend/app/adapter/sqldb/user_short_link.go
  backend/app/adapter/sqldb/user_short_link_integration_test.go
Labels: maintainability

#797 Remove canonical meta tag from index.html
  frontend/public/index.html
Labels: maintainability, size/XS

#799 Add type column to feature toggle table
  backend/app/adapter/sqldb/featuretoggle.go
  backend/app/adapter/sqldb/migration/25_add_type_to_feature_toggle_table.sql
  backend/app/adapter/sqldb/table/featuretoggle.go
  backend/app/entity/toggle.go
Labels: enhancement, size/S

#800 Add view admin panel permission to different user roles
  backend/app/usecase/authorizer/authorizer.go
  backend/app/usecase/authorizer/rbac/permission/permission.go
  backend/app/usecase/authorizer/rbac/role/role.go
Labels: enhancement, size/S

#802 Rename tables in backend
  backend/app/adapter/sqldb/short_link.go
  backend/app/adapter/sqldb/short_link_integration_test.go
  backend/app/adapter/sqldb/table/short_link.go
  backend/app/adapter/sqldb/table/user_short_link.go
  backend/app/adapter/sqldb/user_short_link.go
  backend/app/adapter/sqldb/user_short_link_integration_test.go
Labels: size/L

#804 Rename URL to ShortLink in sqldb package
  backend/app/adapter/sqldb/short_link.go
  backend/app/adapter/sqldb/short_link_integration_test.go
  backend/app/adapter/sqldb/user_short_link.go
  backend/app/adapter/sqldb/user_short_link_integration_test.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: size/L

#805 Rename url to shortlink in entity
  backend/app/adapter/gqlapi/api_test.go
  backend/app/adapter/gqlapi/resolver/authmutation.go
  backend/app/adapter/gqlapi/resolver/authquery.go
  backend/app/adapter/gqlapi/resolver/authquery_test.go
  backend/app/adapter/gqlapi/resolver/query_test.go
  backend/app/adapter/gqlapi/resolver/url.go
  backend/app/adapter/gqlapi/resolver/url_test.go
  backend/app/adapter/routing/handle.go
  backend/app/adapter/sqldb/short_link.go
  backend/app/adapter/sqldb/short_link_integration_test.go
  backend/app/adapter/sqldb/user_short_link.go
  backend/app/entity/shortlink.go
  backend/app/entity/url.go
  backend/app/usecase/instrumentation/instrumentation.go
  backend/app/usecase/repository/url.go
  backend/app/usecase/repository/url_fake.go
  backend/app/usecase/repository/userurl.go
  backend/app/usecase/repository/userurl_fake.go
  backend/app/usecase/url/urlcreator.go
  backend/app/usecase/url/urlcreator_test.go
  backend/app/usecase/url/urlretriever.go
  backend/app/usecase/url/urlretriever_test.go
Labels: size/XL

#717 Add col names prop to Table & add col names to UserShortLinksSection
  frontend/src/component/pages/shared/UserShortLinksSection.scss
  frontend/src/component/pages/shared/UserShortLinksSection.tsx
  frontend/src/component/ui/Table.scss
  frontend/src/component/ui/Table.tsx
Labels: hold, size/M

#806 rename usecase/repository
  backend/app/adapter/gqlapi/api_test.go
  backend/app/adapter/gqlapi/resolver/authmutation.go
  backend/app/adapter/gqlapi/resolver/authquery_test.go
  backend/app/adapter/gqlapi/resolver/query_test.go
  backend/app/adapter/sqldb/short_link.go
  backend/app/adapter/sqldb/short_link_integration_test.go
  backend/app/adapter/sqldb/user_short_link.go
  backend/app/usecase/repository/shortlink.go
  backend/app/usecase/repository/shortlink_fake.go
  backend/app/usecase/repository/url.go
  backend/app/usecase/repository/url_fake.go
  backend/app/usecase/repository/usershortlink.go
  backend/app/usecase/repository/usershortlink_fake.go
  backend/app/usecase/repository/userurl.go
  backend/app/usecase/repository/userurl_fake.go
  backend/app/usecase/url/urlcreator.go
  backend/app/usecase/url/urlcreator_test.go
  backend/app/usecase/url/urlretriever.go
  backend/app/usecase/url/urlretriever_test.go
  backend/dep/wire.go
Labels: size/XL

#810 Add meta tags to short_link table
  backend/app/adapter/sqldb/migration/26_add_meta_tags_to_url.sql
Labels: enhancement, size/S

#813 Fix http error
  frontend/package.json
  frontend/src/service/HTTP.service.ts
  frontend/src/service/ShortHTTP.api.ts
  frontend/yarn.lock
Labels: size/S

#814 deploy
  frontend/package.json
  frontend/src/service/HTTP.service.ts
  frontend/src/service/ShortHTTP.api.ts
  frontend/yarn.lock
Labels: size/S

#817 Separate out withFeatureToggle HOC component
  frontend/src/component/UIFactory.tsx
  frontend/src/component/hoc/withFeatureToggle.tsx
Labels: refactor, size/M

#818 Add Auth HOC to wrap authorized pages
  frontend/src/component/hoc/withPageAuth.tsx
Labels: enhancement, size/M

#815 Rename URL to ShortLink in usecase directory
  backend/app/adapter/gqlapi/api_test.go
  backend/app/adapter/gqlapi/resolver/authmutation.go
  backend/app/adapter/gqlapi/resolver/authquery.go
  backend/app/adapter/gqlapi/resolver/authquery_test.go
  backend/app/adapter/gqlapi/resolver/error.go
  backend/app/adapter/gqlapi/resolver/mutation.go
  backend/app/adapter/gqlapi/resolver/query.go
  backend/app/adapter/gqlapi/resolver/query_test.go
  backend/app/adapter/gqlapi/resolver/resolver.go
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
  backend/app/usecase/instrumentation/instrumentation.go
  backend/app/usecase/risk/blacklist_fake.go
  backend/app/usecase/shortlink/creator.go
  backend/app/usecase/shortlink/creator_test.go
  backend/app/usecase/shortlink/retriever.go
  backend/app/usecase/shortlink/retriever_test.go
  backend/app/usecase/url/urlretriever.go
  backend/dep/provider/routes.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: size/XL

#819 deploy
  backend/app/adapter/gqlapi/api_test.go
  backend/app/adapter/gqlapi/resolver/authmutation.go
  backend/app/adapter/gqlapi/resolver/authquery.go
  backend/app/adapter/gqlapi/resolver/authquery_test.go
  backend/app/adapter/gqlapi/resolver/error.go
  backend/app/adapter/gqlapi/resolver/mutation.go
  backend/app/adapter/gqlapi/resolver/query.go
  backend/app/adapter/gqlapi/resolver/query_test.go
  backend/app/adapter/gqlapi/resolver/resolver.go
  backend/app/adapter/routing/handle.go
  backend/app/adapter/routing/route.go
  backend/app/usecase/instrumentation/instrumentation.go
  backend/app/usecase/risk/blacklist_fake.go
  backend/app/usecase/shortlink/creator.go
  backend/app/usecase/shortlink/creator_test.go
  backend/app/usecase/shortlink/retriever.go
  backend/app/usecase/shortlink/retriever_test.go
  backend/app/usecase/url/urlretriever.go
  backend/dep/provider/routes.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
  frontend/src/component/UIFactory.tsx
  frontend/src/component/hoc/withFeatureToggle.tsx
  frontend/src/component/hoc/withPageAuth.tsx
Labels: size/XL
