Repository short-d/short, pull requests merged in 2020-03, with the labels that each got.

#508 Add sign out button
  frontend/src/component/pages/Home.tsx
  frontend/src/component/pages/shared/Header.scss
  frontend/src/component/pages/shared/Header.tsx
Labels: enhancement

#514 Hide sign out button when user is not signed in
  frontend/src/component/pages/Home.tsx
  frontend/src/component/pages/shared/Header.tsx
Labels: bug

#518 Replace KeyGenerator interface with concrete implementation
  backend/app/adapter/graphql/graphql_test.go
  backend/app/adapter/kgs/kgs.go
  backend/app/usecase/account/linker_test.go
  backend/app/usecase/keygen/keygen.go
  backend/app/usecase/keygen/keygen_fake.go
  backend/app/usecase/keygen/keygen_test.go
  backend/app/usecase/keygen/remote.go
  backend/app/usecase/service/keyfetcher.go
  backend/app/usecase/service/keyfetcher_fake.go
  backend/app/usecase/url/urlcreator_test.go
  backend/dep/provider/keygen.go
  backend/dep/wire.go
  backend/dep/wire_gen.go
Labels: enhancement

#516 Add search bar
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/Home.tsx
  frontend/src/component/pages/shared/Header.scss
  frontend/src/component/pages/shared/Header.tsx
  frontend/src/component/styles/color.scss
  frontend/src/component/styles/shadow.scss
  frontend/src/component/ui/SearchBar.scss
  frontend/src/component/ui/SearchBar.tsx
  frontend/src/dep.ts
  frontend/src/service/Captcha.service.ts
  frontend/src/service/FeatureDecision.service.ts
  frontend/src/service/Search.service.ts
  frontend/src/service/StaticConfigDecision.service.ts
Labels: enhancement

#524 Fix the missed dependency
  frontend/package.json
  frontend/yarn.lock
Labels: dependencies

#532 Fixed malformatted code
  backend/app/usecase/account/linker_test.go
Labels: maintainability

#530 Add ChangeLogModal
  frontend/package.json
  frontend/src/component/styles/center.scss
  frontend/src/component/styles/color.scss
  frontend/src/component/styles/scrollbar.scss
  frontend/src/component/ui/ChangeLogModal.scss
  frontend/src/component/ui/ChangeLogModal.tsx
  frontend/src/component/ui/Modal.scss
  frontend/src/entity/Update.tsx
  frontend/yarn.lock
Labels: React, enhancement

#534 Add toggle component
  frontend/src/component/ui/Toggle.scss
  frontend/src/component/ui/Toggle.tsx
Labels: size/L

#540 Remove unnecessary complexity
  backend/app/usecase/presenter.go
  backend/app/usecase/presenter_mock.go
  backend/app/usecase/usecase.go
  backend/app/usecase/usecase_test.go
Labels: maintainability

#531 Add condition to not display Get Extension Notice when already installed
  frontend/.env.development
  frontend/.env.production
  frontend/.env.staging
  frontend/.env.test
  frontend/package.json
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/Home.tsx
  frontend/src/dep.ts
  frontend/src/service/ChromeExtension.service.ts
  frontend/yarn.lock
Labels: React, enhancement, size/M

#543 Implement debouncing in search bar using rxjs
  frontend/package.json
  frontend/src/component/ui/SearchBar.tsx
  frontend/yarn.lock
Labels: React, size/L

#547 Invalid extension_id error in dev and staging phase
  .drone.yml
  frontend/.env.production
  frontend/.env.staging
  frontend/.env.test
  frontend/package.json
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/Home.tsx
  frontend/src/dep.ts
  frontend/src/service/ChromeExtension.service.ts
  frontend/src/service/extensionService/BrowserExtension.factory.ts
  frontend/src/service/extensionService/BrowserExtension.service.ts
  frontend/src/service/extensionService/ChromeExtension.service.ts
  frontend/src/service/extensionService/DefaultExtension.service.ts
  frontend/yarn.lock
Labels: size/L

#548 Add rohithbalaji123 as code owner for TypeScript
  .github/CODEOWNERS
Labels: size/XS

#549 deploy
  .drone.yml
  .github/CODEOWNERS
  frontend/.env.development
  frontend/package.json
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/Home.tsx
  frontend/src/component/ui/SearchBar.tsx
  frontend/src/dep.ts
  frontend/src/service/extensionService/BrowserExtension.factory.ts
  frontend/src/service/extensionService/BrowserExtension.service.ts
  frontend/src/service/extensionService/ChromeExtension.service.ts
  frontend/src/service/extensionService/DefaultExtension.service.ts
  frontend/yarn.lock
Labels: size/L

#544 Make app responsive
  frontend/src/component/form/TextField.scss
  frontend/src/component/pages/Home.scss
  frontend/src/component/pages/Home.tsx
  frontend/src/component/pages/shared/Header.scss
  frontend/src/component/styles/layouts.scss
Labels: React, enhancement, size/M

#539 Added GetByAliases function in db and repository
  backend/app/adapter/db/url.go
  backend/app/adapter/db/url_integration_test.go
  backend/app/usecase/repository/url.go
  backend/app/usecase/repository/url_fake.go
Labels: size/M

#552 Support retrieving user ID from Facebook account
  backend/app/adapter/facebook/account.go
  backend/app/adapter/facebook/account_integration_test.go
  backend/app/adapter/github/identityprovider_integration_test.go
Labels: enhancement, size/S

#550 Add ChangeLogModal to Footer
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/Home.tsx
  frontend/src/component/pages/shared/Footer.tsx
  frontend/src/component/ui/ChangeLogModal.scss
  frontend/src/component/ui/ChangeLogModal.tsx
  frontend/src/component/ui/ViewChangeLogButton.tsx
  frontend/src/service/FeatureDecision.service.ts
  frontend/src/service/StaticConfigDecision.service.ts
  frontend/src/service/extensionService/ChromeExtension.service.ts
Labels: size/L

#554 Create short link refactor
  frontend/src/component/pages/Home.scss
  frontend/src/component/pages/Home.tsx
  frontend/src/component/pages/shared/CreateShortLinkSection.scss
  frontend/src/component/pages/shared/CreateShortLinkSection.tsx
  frontend/src/component/pages/shared/Footer.tsx
Labels: size/L

#555 deploy
  backend/app/adapter/db/url.go
  backend/app/adapter/db/url_integration_test.go
  backend/app/adapter/facebook/account.go
  backend/app/adapter/facebook/account_integration_test.go
  backend/app/adapter/github/identityprovider_integration_test.go
  backend/app/usecase/repository/url.go
  backend/app/usecase/repository/url_fake.go
  frontend/src/component/UIFactory.tsx
  frontend/src/component/form/TextField.scss
  frontend/src/component/pages/Home.scss
  frontend/src/component/pages/Home.tsx
  frontend/src/component/pages/shared/CreateShortLinkSection.scss
  frontend/src/component/pages/shared/CreateShortLinkSection.tsx
  frontend/src/component/pages/shared/Footer.tsx
  frontend/src/component/pages/shared/Header.scss
  frontend/src/component/styles/layouts.scss
  frontend/src/component/ui/ChangeLogModal.scss
  frontend/src/component/ui/ChangeLogModal.tsx
  frontend/src/component/ui/ViewChangeLogButton.tsx
  frontend/src/service/FeatureDecision.service.ts
  frontend/src/service/StaticConfigDecision.service.ts
  frontend/src/service/extensionService/ChromeExtension.service.ts
Labels: size/XL

#558 Add IsIDExist to User repo
  backend/app/adapter/db/user.go
  backend/app/adapter/db/user_integration_test.go
  backend/app/usecase/repository/user.go
  backend/app/usecase/repository/user_fake.go
Labels: size/M

#560 Add ChangeLogService
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/Home.tsx
  frontend/src/dep.ts
  frontend/src/service/ChangeLog.service.ts
Labels: React, size/M

#561 deploy
  backend/app/adapter/db/user.go
  backend/app/adapter/db/user_integration_test.go
  backend/app/usecase/repository/user.go
  backend/app/usecase/repository/user_fake.go
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/Home.tsx
  frontend/src/dep.ts
  frontend/src/service/ChangeLog.service.ts
  frontend/yarn.lock
Labels: size/L

#562 Fix autofill long link bug
  frontend/src/component/pages/Home.tsx
Labels: bug, size/XS

#563 Fix autofill long link bug (#557)
  frontend/src/component/pages/Home.tsx
Labels: size/XS

#564 Add gofmt to code formatters
  backend/app/adapter/db/url_integration_test.go
  backend/scripts/format
Labels: maintainability, size/XS

#565 Report test coverage for the frontend
  .drone.yml
  Dockerfile-backend-coverage
  Dockerfile-frontend-coverage
  frontend/package.json
  frontend/scripts/code-coverage
  frontend/yarn.lock
  scripts/backend-report-coverage
  scripts/frontend-report-coverage
  scripts/report-coverage
Labels: size/L

#577 Add GetUserByID to User repo
  backend/app/adapter/db/user.go
  backend/app/adapter/db/user_integration_test.go
  backend/app/usecase/repository/user.go
  backend/app/usecase/repository/user_fake.go
Labels: Go, enhancement, size/L

#579 Add unit tests for Button
  frontend/package.json
  frontend/src/component/ui/Button.spec.tsx
  frontend/yarn.lock
Labels: maintainability, size/L

#580 Add unit tests for ViewChangeLogButton
  frontend/src/component/ui/ViewChangeLogButton.spec.tsx
Labels: size/L

#584 Turn off verbose log for unit tests and integration tests
  backend/scripts/integration-test
  backend/scripts/unit-test
Labels: maintainability, size/XS

#587 Add unit tests for Section
  frontend/src/component/ui/Section.spec.tsx
Labels: maintainability, size/S

#586 Add unit tests for Notice
  frontend/src/component/ui/Notice.spec.tsx
Labels: maintainability, size/S

#589 Fix modal keep showing up bug
  frontend/src/component/pages/Home.tsx
  frontend/src/component/ui/Modal.scss
  frontend/src/component/ui/Modal.spec.tsx
  frontend/src/component/ui/Modal.tsx
Labels: size/L

#591 deploy
  .drone.yml
  Dockerfile-backend-coverage
  Dockerfile-frontend-coverage
  backend/app/adapter/db/url_integration_test.go
  backend/app/adapter/db/user.go
  backend/app/adapter/db/user_integration_test.go
  backend/app/usecase/repository/user.go
  backend/app/usecase/repository/user_fake.go
  backend/scripts/format
  backend/scripts/integration-test
  backend/scripts/unit-test
  frontend/package.json
  frontend/scripts/code-coverage
  frontend/src/component/pages/Home.tsx
  frontend/src/component/ui/Button.spec.tsx
  frontend/src/component/ui/Modal.scss
  frontend/src/component/ui/Modal.spec.tsx
  frontend/src/component/ui/Modal.tsx
  frontend/src/component/ui/Notice.spec.tsx
  frontend/src/component/ui/Section.spec.tsx
  frontend/src/component/ui/ViewChangeLogButton.spec.tsx
  frontend/yarn.lock
  scripts/backend-report-coverage
  scripts/frontend-report-coverage
  scripts/report-coverage
Labels: size/XL

#592 Update README.md
  README.md
Labels: documentation, size/S

#585 Add instruction for weekly standups to contributing.md
  CONTRIBUTING.md
Labels: documentation, size/S

#578 Add unit tests for ChangeLogModal
  frontend/src/component/ui/ChangeLogModal.spec.tsx
  frontend/src/component/ui/ChangeLogModal.tsx
  frontend/src/component/ui/Notice.spec.tsx
  frontend/src/component/ui/Section.spec.tsx
Labels: maintainability, size/L

#593 Add test script for frontend
  frontend/scripts/test
Labels: maintainability, size/XS

#594 Fix short link usage original URL display bug
  frontend/src/component/pages/Home.tsx
  frontend/src/component/pages/shared/CreateShortLinkSection.tsx
  frontend/src/entity/Url.tsx
  frontend/src/service/Url.service.ts
Labels: size/M

#598 Add clipboard service to copy text to user's clipboard
  frontend/src/dep.ts
  frontend/src/service/clipboardService/Clipboard.service.factory.ts
  frontend/src/service/clipboardService/Clipboard.service.ts
  frontend/src/service/clipboardService/NativeClipboard.service.ts
  frontend/src/service/clipboardService/SimulatedClipboard.service.ts
  frontend/src/service/extensionService/BrowserExtension.factory.ts
  frontend/src/service/extensionService/BrowserExtension.service.ts
Labels: size/M

#600 Add ChangeLog repository
  backend/app/adapter/db/change_log.go
  backend/app/adapter/db/change_log_integration_test.go
  backend/app/adapter/db/migration/12_create_changelog_table.sql
  backend/app/adapter/db/table/changelog.go
  backend/app/entity/change.go
  backend/app/usecase/repository/change_log.go
Labels: Go, enhancement, size/L

#601 Fix code coverage report
  backend/scripts/code-coverage
Labels: size/XS

#597 Add toast component to show notifications
  frontend/src/component/styles/center.scss
  frontend/src/component/styles/color.scss
  frontend/src/component/styles/layer.scss
  frontend/src/component/ui/Modal.scss
  frontend/src/component/ui/SearchBar.scss
  frontend/src/component/ui/Toast.scss
  frontend/src/component/ui/Toast.spec.tsx
  frontend/src/component/ui/Toast.tsx
Labels: enhancement, size/L

#603 Integrate Clipboard Service to copy shortened url
  frontend/.env.testing
  frontend/src/component/UIFactory.tsx
  frontend/src/component/pages/Home.tsx
  frontend/src/dep.ts
Labels: enhancement, size/M

#602 Add ChangeLog usecase
  backend/app/adapter/db/change_log_integration_test.go
  backend/app/entity/change.go
  backend/app/usecase/changelog/changelog.go
  backend/app/usecase/changelog/changelog_test.go
  backend/app/usecase/repository/change_log_fake.go
Labels: Go, enhancement, size/L

#606 deploy
  backend/app/adapter/db/change_log_integration_test.go
  backend/app/entity/change.go
  backend/app/usecase/changelog/changelog.go
  backend/app/usecase/changelog/changelog_test.go
  backend/app/usecase/repository/change_log_fake.go
Labels: size/L

#609 Add testing env configurations
  .drone.yml
  frontend/.env.testing
  frontend/package.json
Labels: size/M
